import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {enqueueArchive,collectArchiveBatch,archiveStatus,archiveLinks,archivePageUrl} from '../src/archive-collection-v3.38.0.js';
const date='2026-10-03',cardUrl='https://www.jra.go.jp/JRADB/accessD.html?CNAME=pw01dde1008202604010120261003%2FAB';
const card='<h2>3歳未勝利</h2><p>コース：1600メートル（芝） 2頭</p><table>'+['アーカイブエース','アーカイブスター'].map((name,i)=>`<tr><td>${i+1}</td><td>${i+1}</td><td><a href="/horse">${name}</a>父：シード 母：シード</td><td>牡3 57.0kg <a href="/jockey">騎手</a></td></tr>`).join('')+'</table>';
const program=`<h2>4回京都1日</h2><table><tr><td>1レース 3歳未勝利 1600（芝） 10時00分</td></tr></table><a href="${cardUrl}">出馬表</a>`;
const response=body=>new Response(body,{headers:{'content-type':'text/html; charset=utf-8'}});
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE jra_race_program(program_key TEXT PRIMARY KEY,race_date TEXT,venue TEXT,meeting_no INTEGER,day_no INTEGER,race_no INTEGER,race_label TEXT,surface TEXT,distance INTEGER,start_time TEXT,grade TEXT,source_url TEXT,fetched_at TEXT);CREATE TABLE jra_races(race_key TEXT PRIMARY KEY,race_date TEXT,venue TEXT,race_no INTEGER,race_name TEXT,surface TEXT,distance INTEGER,source_url TEXT,runner_count INTEGER,fetched_at TEXT);CREATE TABLE jra_runners(race_key TEXT,horse_no INTEGER,frame_no INTEGER,horse_name TEXT,sex TEXT,age INTEGER,assigned_weight REAL,jockey TEXT,trainer TEXT,fetched_at TEXT);');const db={prepare(q){const wrap=(args=[])=>({bind(...a){return wrap(a)},async first(){return sql.prepare(q).get(...args)||null},async all(){return{results:sql.prepare(q).all(...args)}},async run(){const result=sql.prepare(q).run(...args);return{meta:{changes:Number(result.changes)}}}});return wrap()},async batch(ss){sql.exec('BEGIN');try{const result=[];for(const s of ss)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};return{db,sql}}
const start=Date.parse('2026-10-06T07:00:00Z');
test('archive intake rejects future dates and wrong-date or nonofficial links',async()=>{const {db,sql}=fixture();await assert.rejects(()=>enqueueArchive(db,['2026-10-10'],start),/過去日/);await assert.rejects(()=>enqueueArchive(db,['2015-12-31'],start),/過去日/);assert.throws(()=>archivePageUrl(cardUrl,'2026-10-04'),/対象日/);assert.throws(()=>archivePageUrl('https://example.com/card',date),/JRA/);const links=archiveLinks(`<a href="${cardUrl}">ok</a><a href="https://example.com/card">bad</a>`,cardUrl,date);assert.deepEqual(links,[cardUrl]);sql.close()});
test('one official page per batch resumes to a complete historical card with source evidence',async()=>{const {db,sql}=fixture();let stamp=start;const calls=[];const deps={now:()=>stamp,wait:async()=>{},fetcher:async(url,options)=>{calls.push({url,options});return response(options.method==='POST'?card:program)}};await enqueueArchive(db,[date],stamp);const first=await collectArchiveBatch(db,deps);assert.equal(first.externalRequests,1);assert.equal(first.savedCards,0);assert.equal(first.runs[0].programRaces,1);stamp+=61000;const second=await collectArchiveBatch(db,deps);assert.equal(second.externalRequests,1);assert.equal(second.savedCards,1);assert.equal(second.status,'complete');assert.equal(calls[1].options.method,'POST');assert.ok(calls[1].options.body.includes('pw01dde'));assert.equal(sql.prepare('SELECT COUNT(*) n FROM jra_runners').get().n,2);assert.equal(sql.prepare('SELECT source_sha256 FROM lab_card_source_evidence').get().source_sha256.length,64);assert.equal(sql.prepare('SELECT status FROM lab_history_collection_targets').get().status,'pending');stamp+=61000;assert.equal((await collectArchiveBatch(db,deps)).externalRequests,0);assert.equal(calls.length,2);sql.close()});
test('429 pauses the shared source budget and stores a resumable failure',async()=>{const {db,sql}=fixture();await enqueueArchive(db,[date],start);const result=await collectArchiveBatch(db,{now:()=>start,fetcher:async()=>new Response('',{status:429})});assert.equal(result.ok,false);assert.equal(result.externalRequests,1);assert.equal(sql.prepare('SELECT next_batch_at FROM lab_history_collection_budget').get().next_batch_at,start+3600000);assert.equal(sql.prepare('SELECT status FROM lab_archive_collection_pages').get().status,'failed');const later=await collectArchiveBatch(db,{now:()=>start+61000,fetcher:async()=>{throw Error('must not fetch')}});assert.equal(later.status,'cooldown');assert.equal(later.externalRequests,0);sql.close()});
test('incomplete observed frames prevent saving a card even with complete-looking parsed runners',async()=>{const {db,sql}=fixture();let stamp=start;await enqueueArchive(db,[date],stamp);const deps={now:()=>stamp,fetcher:async(url,options)=>response(options.method==='POST'?card.replace('<td>2</td><td>2</td>','<td>2</td>'):program)};await collectArchiveBatch(db,deps);stamp+=61000;const result=await collectArchiveBatch(db,deps);assert.equal(result.savedCards,0);assert.equal(result.ok,false);assert.ok(result.runs.some(x=>x.error?.includes('枠番')));assert.equal((await archiveStatus(db)).targets[0].status,'pending');sql.close()});
test('no published historical card link is reported as blocked, never as an unpublished race',async()=>{const {db,sql}=fixture();await enqueueArchive(db,[date],start);const result=await collectArchiveBatch(db,{now:()=>start,fetcher:async()=>response(program.replace(/<a[\s\S]*$/,''))});assert.equal(result.status,'awaiting-published-card-links');assert.equal(result.savedCards,0);const status=await archiveStatus(db);assert.ok(status.targets[0].error.includes('未発見'));assert.equal(status.targets[0].next_run_at,start+86400000);sql.close()});
