import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {makeCheckpoint,appendCheckpoint,readCheckpoints,compareCheckpoints,reviewPhaseReason,reviewRaceKey} from '../src/comparison-review-v3.42.0.js';
import {initComparison} from '../src/mark-comparison-client-v3.42.0.js';
import {reviewCardContext} from '../src/review-card-context-v3.42.0.js';
import {sha256,runnerFingerprint} from '../src/card-evidence.js';
import app from '../src/index-v3.42.0.js';
const target={date:'2026-10-10',venue:'東京',raceNo:11,names:['エース','スター']};
const stamp=Date.parse('2026-10-06T09:00:00Z'),marks=[{horseName:'エース',mark:'◎'}];
const data=()=>({ok:true,race:{...target},audit:{marked:marks,historySidecar:[]},reviewMeta:{official:false,frameVerified:false},assessment:{modelVersion:'safe-core-1.5',runnerPool:2,scoredRunners:2,trackAssumption:null,allRunners:target.names.map((horseName,i)=>({horseName,referenceRank:i+1,tiedCount:1,assessment:{available:true,evidenceScore:75-i,validFinishRows:4,components:{basicAbilityResults:75,recentPerformanceDevelopment:70,courseDistanceFit:65,ground:null},detail:{ability:{validFinishRows:4},recent:{rows:4},course:{exactDistance:{validFinishRows:2}},ground:{rows:0}}}}))}});
test('checkpoints are immutable local records, never backdated accuracy evidence or inferred frame numbers',()=>{const d=data(),before=JSON.stringify(d);const s=makeCheckpoint(target,d,marks,'initial',stamp);assert.equal(JSON.stringify(d),before);assert.equal(s.rows[0].horseNo,null);assert.equal(s.rows[0].frameNo,null);assert.equal(s.eligibleForAccuracyEvaluation,false);assert.equal(s.officialMarkRevision,false);assert.equal(s.capturedBeforeRaceDay,true);marks[0].mark='△';assert.equal(s.marks[0].mark,'◎');marks[0].mark='◎';assert.equal(makeCheckpoint(target,d,marks,'initial',Date.parse('2026-10-11T00:00:00Z')).retrospective,true);assert.throws(()=>makeCheckpoint({...target,raceNo:1},d,marks),/一致/);});
test('post-draw needs verified frames and race-day uses Japan calendar boundaries',()=>{assert(reviewPhaseReason('post_draw',{},target.date,stamp));assert(reviewPhaseReason('race_day',{frameVerified:true},target.date,stamp));assert.equal(reviewPhaseReason('race_day',{frameVerified:true},target.date,Date.parse('2026-10-09T15:00:00Z')),null);const d=data();d.reviewMeta={official:true,frameVerified:true,roster:[{horseName:'エース',horseNo:1,frameNo:1}]};assert.equal(makeCheckpoint(target,d,marks,'post_draw',stamp).rows[0].frameNo,1);assert.throws(()=>makeCheckpoint(target,data(),marks,'post_draw',stamp),/正式出馬表/);});
test('mark-only changes preserve scores; missing scores stay missing and changed rosters suspend rank deltas',()=>{const d=data(),a=makeCheckpoint(target,d,marks,'initial',stamp),b=makeCheckpoint(target,d,[{horseName:'エース',mark:'△'}],'initial',stamp+1);assert.equal(compareCheckpoints(a,b).changes[0].scoreDelta,0);d.assessment.allRunners[0].assessment.evidenceScore=null;d.assessment.scoredRunners=1;const c=makeCheckpoint(target,d,marks,'initial',stamp+2);assert.equal(compareCheckpoints(a,c).changes[0].scoreDelta,null);assert.equal(compareCheckpoints(a,c).rankComparable,false);d.assessment.allRunners[1].horseName='新顔';const diff=compareCheckpoints(a,makeCheckpoint(target,d,marks,'initial',stamp+3));assert.equal(diff.rosterChanged,true);assert.equal(diff.rankComparable,false);assert.equal(diff.changes.find(r=>r.horseName==='スター').participation,'現在の一覧に不在');assert.equal(diff.changes.find(r=>r.horseName==='新顔').participation,'追加');});
test('bounded checkpoint history deduplicates unchanged views and protects corrupt saved data',()=>{const s=makeCheckpoint(target,data(),marks,'initial',stamp);assert.equal(appendCheckpoint([s],{...s,id:'other',capturedAt:new Date(stamp+1).toISOString()}).length,1);let h=[];for(let i=0;i<25;i++)h=appendCheckpoint(h,{...s,id:String(i),track:String(i)});assert.equal(h.length,20);assert.equal(h[0].id,'5');assert.equal(readCheckpoints(JSON.stringify(h),reviewRaceKey(target)).length,20);assert.throws(()=>readCheckpoints('{broken',reviewRaceKey(target)),/上書きせず/);assert.throws(()=>readCheckpoints(JSON.stringify([{...s,raceKey:'other'}]),reviewRaceKey(target)),/上書きせず/);});
function page(storage=new Map()){const nodes=new Map(),selects=target.names.map(horse=>({dataset:{horse},value:''}));const node=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:'',value:'',disabled:false,options:[],listeners:{},addEventListener(k,f){this.listeners[k]=f;},querySelectorAll(){return selects;}});return nodes.get(id);};node('comparisonTarget').textContent=JSON.stringify(target);return{nodes,selects,document:{getElementById:node},storage:storage===null?null:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},store:storage};}
test('browser captures after comparison, invalidates on edit and restores history after reload',async()=>{const p=page();const c=initComparison({...p,now:()=>stamp,fetcher:async()=>({ok:true,json:async()=>data()}),setTimer:()=>1,clearTimer:()=>{}});p.selects[0].value='◎';assert.equal(p.nodes.get('recordComparison').disabled,true);await c.compare();assert.equal(p.nodes.get('recordComparison').disabled,false);c.recordCheckpoint();assert(p.nodes.get('reviewCount').textContent.includes('1件'));c.recordCheckpoint();assert(p.nodes.get('recordStatus').textContent.includes('記録済み'));p.selects[0].value='△';c.changed();assert.equal(p.nodes.get('recordComparison').disabled,true);await c.compare();assert(p.nodes.get('reviewDelta').innerHTML.includes('◎ → △'));c.recordCheckpoint();assert(p.nodes.get('reviewCount').textContent.includes('2件'));const p2=page(p.store);initComparison({...p2,now:()=>stamp,fetcher:async()=>({ok:true,json:async()=>data()})});assert(p2.nodes.get('reviewCount').textContent.includes('2件'));assert.equal(p2.selects[0].value,'△');});
test('corrupt history and unavailable storage cannot be falsely enabled by rendering',async()=>{for(const corrupt of [true,false]){const p=page(corrupt?new Map([['keiba-labo:comparison-history:v1:'+reviewRaceKey(target),'{bad']]):null);const c=initComparison({...p,now:()=>stamp,fetcher:async()=>({ok:true,json:async()=>data()})});p.selects[0].value='◎';await c.compare();assert.equal(p.nodes.get('recordComparison').disabled,true);c.recordCheckpoint();assert(p.nodes.get('recordStatus').textContent.includes('保留'));if(corrupt)assert.equal(p.store.get('keiba-labo:comparison-history:v1:'+reviewRaceKey(target)),'{bad');}});
test('quota failures preserve existing history and never report success',async()=>{const p=page();const c=initComparison({...p,now:()=>stamp,fetcher:async()=>({ok:true,json:async()=>data()})});p.selects[0].value='◎';await c.compare();p.storage.setItem=()=>{throw Error('quota');};c.recordCheckpoint();assert(p.nodes.get('recordStatus').textContent.includes('記録できません'));assert(p.nodes.get('reviewCount').textContent.includes('0件'));});
test('frame context requires current full-field fingerprint and makes only two read queries',async()=>{const runners=[{horse_no:1,frame_no:1,horse_name:'エース',age:2},{horse_no:2,frame_no:2,horse_name:'スター',age:2}];const e={runner_count:2,horse_numbers_observed:1,frames_observed:1,declared_count:2,source_row_count:2,parsed_count:2,card_fetched_at:'now',fetched_at:'now',runner_sha256:await sha256(runnerFingerprint(runners)),source_sha256:'source'};let calls=0;const db={prepare(sql){calls++;assert(sql.startsWith('SELECT'));return{bind(){return this;},all:async()=>({results:runners}),first:async()=>e};}};assert.equal((await reviewCardContext(db,target,{official:true},stamp)).frameVerified,true);assert.equal(calls,2);e.runner_count=3;assert.equal((await reviewCardContext(db,target,{official:true},stamp)).frameVerified,false);e.runner_count=2;e.runner_sha256='stale';assert.equal((await reviewCardContext(db,target,{official:true},stamp)).frameVerified,false);calls=0;assert.equal((await reviewCardContext(db,target,{official:false},stamp)).frameVerified,false);assert.equal(calls,0);});
test('served review/client modules exactly match source and parse independently of bundler naming',async()=>{const review=await(await app.fetch(new Request('https://test/lab/comparison-review.js'),{},{})).text(),client=await(await app.fetch(new Request('https://test/lab/mark-comparison-client.js'),{},{})).text();assert.equal(review,await readFile(new URL('../src/comparison-review-v3.42.0.js',import.meta.url),'utf8'));assert.equal(client,(await readFile(new URL('../src/mark-comparison-client-v3.42.0.js',import.meta.url),'utf8')).replace("'./mark-comparison-core-v3.41.0.js'","'/lab/mark-comparison-core.js'").replace("'./comparison-review-v3.42.0.js'","'/lab/comparison-review.js'")+'\ninitComparison({document});\n');new Function(review.replaceAll('export ',''));new Function(client.replace(/^import[^;]+;\n/gm,'').replace('export ',''));const pageText=await(await app.fetch(new Request('https://test/lab/expected-preview'),{},{})).text();assert(pageText.includes('今の比較を記録'));assert(pageText.includes('reviewBaseline'));});
