import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {ensureCollectionTables,collectHistoryBatch} from '../src/history-collection-v3.37.0.js';
import {expectedHistoryContext,expectedHistoryStatus,collectUpcomingExpectedHistory,scheduledWeekendHistory,upcomingExpectedSources} from '../src/expected-history-collection-v3.46.0.js';
import app from '../src/index-v3.46.0.js';
const stamp=Date.parse('2026-10-07T00:00:00Z');
const source={snapshotId:'test-v1',date:'2026-10-10',venue:'東京',raceNo:11,raceName:'試験',age:2,names:['HorseA','HorseB']};
const profile='https://www.jra.go.jp/JRADB/accessU.html?CNAME=pw01dud002024100001/AA';
async function fixture(){const sql=new DatabaseSync(':memory:');sql.exec("CREATE TABLE jra_races(race_key TEXT,race_date TEXT,venue TEXT,race_no INTEGER,race_name TEXT,source_url TEXT,runner_count INTEGER);CREATE TABLE jra_runners(race_key TEXT,horse_no INTEGER,horse_name TEXT,age INTEGER);INSERT INTO jra_races VALUES('prior','2026-09-01','東京',5,'前走','https://www.jra.go.jp/card',2);INSERT INTO jra_runners VALUES('prior',1,'HorseA',2),('prior',2,'HorseB',2);");const db={prepare(q){const wrap=(args=[])=>({bind(...a){return wrap(a)},async first(){return sql.prepare(q).get(...args)||null},async all(){return{results:sql.prepare(q).all(...args)}},async run(){const r=sql.prepare(q).run(...args);return{meta:{changes:Number(r.changes)}}}});return wrap()},async batch(ss){const out=[];for(const s of ss)out.push(await s.run());return out;}};await ensureCollectionTables(db);sql.prepare('INSERT INTO lab_history_profile_links VALUES(?,?,?,?,?,?)').run('prior','HorseA',2,profile,'https://www.jra.go.jp/card',stamp-100000);return{db,sql};}
const row=date=>'<tr>'+[date,'東京','過去レース','芝1600','良','12','2','1','騎手','55','450(+0)','1:34.0','111','勝馬'].map(x=>'<td>'+x+'</td>').join('')+'</tr>';
const html='<h1>HorseA</h1><table>'+row('2026年10月10日')+row('2026年9月1日')+row('2025年9月1日')+'</table>';
test('pre-card collector uses one known JRA profile, excludes target date, never creates official card',async()=>{const {db,sql}=await fixture(),urls=[];const deps={sources:[source],now:()=>stamp,wait:async()=>{},fetcher:async url=>{urls.push(url);return new Response(html,{headers:{'content-type':'text/html; charset=utf-8'}});}};const r=await scheduledWeekendHistory(db,deps);assert.equal(r.stage,'expected-runner-prior-history');assert.equal(r.attempted,1);assert.equal(r.externalRequests,1);assert.deepEqual(urls,[profile]);assert.equal(r.before.runners[0].horseNo,null);assert.equal(sql.prepare('SELECT COUNT(*) n FROM jra_races').get().n,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM jra_past_performances').get().n,1);assert.equal(sql.prepare('SELECT race_date FROM jra_past_performances').get().race_date,'2026-09-01');const status=await expectedHistoryStatus(db,stamp,[source]);assert.equal(status.races[0].withStoredHistory,1);assert.equal(status.races[0].profileLinksFound,1);assert.equal(status.races[0].runners[1].profileLinkKnown,false);assert.equal(status.guardrails.externalRequests,0);assert.equal((await collectUpcomingExpectedHistory(db,{...deps,now:()=>stamp+60000})).externalRequests,0);assert.equal(urls.length,1);sql.close();});
test('missing, external, conflicting, wrong-cohort and changed-card links are held without guessed fetches',async()=>{for(const kind of ['missing','external','cohort','card','conflict']){const {db,sql}=await fixture();if(kind==='missing')sql.exec('DELETE FROM lab_history_profile_links');if(kind==='external')sql.exec("UPDATE lab_history_profile_links SET profile_url='https://example.com/horse'");if(kind==='cohort')sql.exec('UPDATE jra_runners SET age=3');if(kind==='card')sql.exec("UPDATE jra_races SET source_url='https://www.jra.go.jp/changed'");if(kind==='conflict'){sql.exec("INSERT INTO jra_races SELECT 'other',race_date,venue,6,race_name,source_url,1 FROM jra_races;INSERT INTO jra_runners VALUES('other',1,'HorseA',2)");sql.prepare('INSERT INTO lab_history_profile_links VALUES(?,?,?,?,?,?)').run('other','HorseA',2,profile.replace('100001','100002'),'https://www.jra.go.jp/card',stamp);}const c=await expectedHistoryContext(db,source);assert.equal(c.runners[0].profile_url,null,kind);let calls=0;const r=await collectUpcomingExpectedHistory(db,{sources:[source],now:()=>stamp,fetcher:async()=>{calls++;throw Error('must not fetch');}});assert.equal(r.externalRequests,0);assert.equal(calls,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM lab_history_collection_receipts').get().n,0);sql.close();}});
test('expected and ordinary history share global 429 pause',async()=>{const {db,sql}=await fixture();let calls=0;const deps={sources:[source],now:()=>stamp,fetcher:async()=>{calls++;return new Response('',{status:429});}};assert.equal((await scheduledWeekendHistory(db,deps)).externalRequests,1);const r=await scheduledWeekendHistory(db,{...deps,now:()=>stamp+61000});assert.equal(r.externalRequests,0);const ordinary=await collectHistoryBatch(db,{date:'2026-09-01',venue:'東京',raceNo:5},{...deps,now:()=>stamp+61000});assert.equal(ordinary.status,'cooldown');assert.equal(calls,1);assert.equal(sql.prepare('SELECT next_batch_at FROM lab_history_collection_budget').get().next_batch_at,stamp+3600000);sql.close();});
test('published complete formal card takes priority and incomplete card cannot suppress pre-card work',async()=>{const {db,sql}=await fixture();sql.exec("INSERT INTO jra_races VALUES('future','2026-10-10','東京',11,'試験','https://www.jra.go.jp/card',2);INSERT INTO jra_runners VALUES('future',1,'HorseA',2)");assert.equal((await expectedHistoryStatus(db,stamp,[source])).races[0].formalCardSaved,false);sql.exec("INSERT INTO jra_runners VALUES('future',2,'HorseB',2)");let calls=0;const r=await collectUpcomingExpectedHistory(db,{sources:[source],now:()=>stamp,fetcher:async()=>{calls++;throw Error();}});assert.equal(r.status,'idle');assert.equal(calls,0);assert.equal((await expectedHistoryStatus(db,stamp,[source])).races[0].formalCardSaved,true);sql.close();});
test('dated sources expire after race day and database errors fail closed',async()=>{assert.equal(upcomingExpectedSources(Date.parse('2026-10-11T00:00:00Z'),[source]).length,0);assert.equal(upcomingExpectedSources(stamp,[{...source,date:'2026-10-20'}]).length,0);await assert.rejects(expectedHistoryStatus({prepare(){throw Error('database unavailable');}},stamp,[source]),/database unavailable/);const r=await app.fetch(new Request('https://test/v1/lab/expected-history-status'),{},{});assert.equal(r.status,503);assert.equal((await r.json()).ok,false);});
test('same-name profile cannot ingest maintenance text as zero history',async()=>{const {db,sql}=await fixture();const r=await collectUpcomingExpectedHistory(db,{sources:[source],now:()=>stamp,fetcher:async()=>new Response('<h1>HorseA</h1>maintenance',{headers:{'content-type':'text/html; charset=utf-8'}})});assert.equal(r.results[0].status,'failed');assert.match(r.results[0].error,/履歴ゼロ/);assert.equal(sql.prepare('SELECT COUNT(*) n FROM jra_past_performances').get().n,0);sql.close();});
