import test from 'node:test';import assert from 'node:assert/strict';
import {auditLearning} from '../src/learning-readiness-v3.34.0.js';
async function fixture(date='2026-10-04',track='良'){const key=date+'|京都|11';const snapshot={race:{raceKey:key,date,trackCondition:track,runnerCount:2},sealKind:'prospective-holdout',quality:{validationCreditEligible:true,outcomeCountAtSeal:0},runners:[{horseNo:1,horseName:'馬A',rank:1,components:{basicAbilityResults:70,recentPerformanceDevelopment:80}},{horseNo:2,horseName:'馬B',rank:2,components:{basicAbilityResults:50,recentPerformanceDevelopment:60}}]};const raw=JSON.stringify(snapshot);const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))].map(x=>x.toString(16).padStart(2,'0')).join('');return{seal:{race_key:key,model_version:'3.3.0-prospective',race_date:date,track_condition:track,seal_kind:'prospective-holdout',snapshot_json:raw,snapshot_sha256:hash,runner_count:2,outcome_count_at_seal:0,future_day_lock:1,sealed_at:new Date(Date.parse(date+'T00:00:00+09:00')-86400000).toISOString()},outcomes:[{race_key:key,horse_no:1,horse_name:'馬A',finish_position:1,finish_status:'finished'},{race_key:key,horse_no:2,horse_name:'馬B',finish_position:2,finish_status:'finished'}]}}
test('empty prospective set never reports learned or zero-percent accuracy',async()=>{const d=await auditLearning();assert.equal(d.strictEvaluatedRaces,0);assert.equal(d.overall.top1WinRate,null);assert.equal(d.automaticTraining,false);assert.equal(d.canStartOfflineExperiment,false)});
test('verified full-pool future-day seal is evaluated without mutation',async()=>{const f=await fixture();const before=JSON.stringify(f);const d=await auditLearning({seals:[f.seal],outcomes:f.outcomes,splitDate:'2026-10-05'});assert.equal(d.strictEvaluatedRaces,1);assert.equal(d.overall.top1WinRate,100);assert.equal(d.training.races,1);assert.equal(d.validation.races,0);assert.equal(JSON.stringify(f),before);assert.equal(d.canStartOfflineExperiment,false)});
test('partial results, wrong horse names and missing winner remain pending',async()=>{const f=await fixture();for(const outcomes of [f.outcomes.slice(0,1),f.outcomes.map((x,i)=>i?x:{...x,horse_name:'別馬'}),f.outcomes.map(x=>({...x,finish_position:2}))]){const d=await auditLearning({seals:[f.seal],outcomes});assert.equal(d.strictEvaluatedRaces,0);assert.equal(d.pendingResultRaces,1);assert.equal(d.overall.top1WinRate,null)}});
test('tampered hashes and same-day or post-outcome seals are excluded',async()=>{const f=await fixture();for(const seal of [{...f.seal,snapshot_json:f.seal.snapshot_json+' '},{...f.seal,sealed_at:'2026-10-04T00:00:00+09:00'},{...f.seal,outcome_count_at_seal:1},{...f.seal,future_day_lock:0}]){const d=await auditLearning({seals:[seal],outcomes:f.outcomes});assert.equal(d.strictEvaluatedRaces,0);assert.equal(d.rejectedSeals,1)}});
test('track is selected before comparison and whole race dates stay disjoint',async()=>{const a=await fixture('2026-10-03'),b=await fixture('2026-10-04'),other=await fixture('2026-10-04','重');other.outcomes[0].finish_position=2;const d=await auditLearning({seals:[a.seal,b.seal,other.seal],outcomes:[...a.outcomes,...b.outcomes],splitDate:'2026-10-04',track:'良'});assert.equal(d.training.races,1);assert.equal(d.validation.races,1);assert.equal(d.overall.races,2);assert.equal(d.policy.splitDate,'2026-10-04')});
import {DatabaseSync} from 'node:sqlite';
import {learningReadiness} from '../src/learning-readiness-v3.34.0.js';
test('SQLite joins only real seals and read-only report never writes database',async()=>{const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE lab_model_locks(race_key TEXT,model_version TEXT,track_condition TEXT,seal_kind TEXT,snapshot_json TEXT,sealed_at TEXT);CREATE TABLE lab_prospective_seals(race_key TEXT,model_version TEXT,track_condition TEXT,race_date TEXT,snapshot_sha256 TEXT,runner_count INTEGER,outcome_count_at_seal INTEGER,future_day_lock INTEGER);CREATE TABLE lab_race_result_details(race_key TEXT,horse_no INTEGER,horse_name TEXT,finish_position INTEGER,finish_status TEXT)');const f=await fixture(),x=f.seal;sql.prepare('INSERT INTO lab_model_locks VALUES(?,?,?,?,?,?)').run(x.race_key,x.model_version,x.track_condition,x.seal_kind,x.snapshot_json,x.sealed_at);sql.prepare('INSERT INTO lab_prospective_seals VALUES(?,?,?,?,?,?,?,?)').run(x.race_key,x.model_version,x.track_condition,x.race_date,x.snapshot_sha256,x.runner_count,0,1);for(const r of f.outcomes)sql.prepare('INSERT INTO lab_race_result_details VALUES(?,?,?,?,?)').run(r.race_key,r.horse_no,r.horse_name,r.finish_position,r.finish_status);const db={prepare(q){return{bind(...args){return{async all(){return{results:sql.prepare(q).all(...args)}},async run(){throw Error('report must never write')}}}}}};const d=await learningReadiness(db,{from:'2026-10-01',to:'2026-10-06',splitDate:'2026-10-04'});assert.equal(d.strictEvaluatedRaces,1);assert.equal(d.validation.races,1);sql.close()});
import {learningPage} from '../src/learning-page-v3.34.0.js';import {Script} from 'node:vm';
test('learning screen scripts compile and explicitly show no automatic learning',()=>{const html=learningPage();for(const [,s] of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Script(s);assert.ok(html.includes('自動学習・評価の重みの更新：未実装'));assert.ok(html.includes('未算出'))});
