import test from 'node:test';import assert from 'node:assert/strict';
import {buildMarkComparison} from '../src/mark-comparison-core-v3.41.0.js';
import {comparisonPage} from '../src/mark-comparison-page-v3.41.0.js';
import app from '../src/index-v3.41.0.js';
import {initComparison} from '../src/mark-comparison-client-v3.41.0.js';
import {readFile} from 'node:fs/promises';
const runner=(horseName,rank,score=75,rows=4,tiedCount=1)=>({horseName,referenceRank:rank,tiedCount,assessment:{available:score!==null,evidenceScore:score,validFinishRows:rows,modelCoveragePct:60,sameCourseDistanceStarts:2,components:{basicAbilityResults:score,recentPerformanceDevelopment:70,courseDistanceFit:65,ground:null},detail:{ability:{validFinishRows:rows},recent:{rows},course:{exactDistance:{validFinishRows:2}},ground:{rows:0}}}});
const fixture=()=>({audit:{marked:[{horseName:'エース',mark:'◎'}],historySidecar:[{horseName:'エース',recent:[{date:'2026-09-01',last3f:null,cornerPositions:null}],warnings:[]}]},assessment:{runnerPool:10,scoredRunners:10,trackAssumption:null,allRunners:[runner('エース',7),runner('スター',1)]}});
test('human marks change the comparison without changing DB scores or reference ranks',()=>{const d=fixture(),before=JSON.stringify(d);assert.equal(buildMarkComparison(d).rows[0].state,'review');assert.equal(buildMarkComparison(d,[{horseName:'エース',mark:'△'}]).rows[0].state,'aligned');assert.equal(JSON.stringify(d),before);const r=buildMarkComparison(d).rows[0];assert.equal(r.reasons[0].rows,4);assert(r.gaps.some(x=>x.includes('上がり3F：0/1')));assert(r.gaps.some(x=>x.includes('通過順：0/1')));assert(r.gaps.some(x=>x.includes('馬場は未確定')));});
test('missing, thin, partial-pool and boundary ties never assert agreement or disagreement',()=>{for(const [edit,state] of [[d=>d.assessment.allRunners[0]=runner('エース',null,null,0),'unavailable'],[d=>d.assessment.allRunners[0]=runner('エース',7,75,2),'thin-history'],[d=>d.assessment.scoredRunners=9,'incomplete-pool'],[d=>d.assessment.allRunners[0]=runner('エース',3,75,4,3),'tie-boundary']]){const d=fixture();edit(d);assert.equal(buildMarkComparison(d).rows[0].state,state);assert.equal(buildMarkComparison(d).summary.held,1);}});
test('removing a reference top horse shows a review reason and tied unmarked candidates stay tied',()=>{const d=fixture();d.assessment.allRunners.push(runner('スカイ',1));const c=buildMarkComparison(d,[{horseName:'スター',mark:'消'}]);assert.equal(c.rows[0].state,'review');assert(c.rows[0].explanation.includes('印を見直す材料'));assert(c.unmarkedCandidates.some(x=>x.horseName==='スカイ'&&x.referenceRank===1));});
test('page embeds escaped targets, auto-change module, browser-only persistence and accessible all-runner table',()=>{const p=comparisonPage({date:'2026-10-10',venue:'東京',raceNo:11,raceName:'<テスト>',surface:'芝',distance:1600,names:['エース','</script><script>危険'],official:true,runners:[{horse_name:'エース',horse_no:1}]});assert(p.includes('初期印を付けると'));assert(p.includes('DBへの印保存ではありません'));assert(p.includes('comparisonTarget'));assert(p.includes('mark-comparison-client.js'));assert(!p.includes('const target='));assert(!p.includes('</script><script>危険'));assert(p.includes('table-scroll'));});
test('served browser modules have valid syntax and use the same comparison rule implementation',async()=>{const core=await(await app.fetch(new Request('https://test/lab/mark-comparison-core.js'),{},{})).text();const client=await(await app.fetch(new Request('https://test/lab/mark-comparison-client.js'),{},{})).text();new Function(core.replace('export function','function'));new Function(client.replace(/^import[^;]+;/,'').replace('export function','function'));assert(core.includes('全馬の履歴補完待ち'));assert(client.includes('now()-old.at<60000'));assert(client.includes('queue.catch'));assert(client.includes('id!==sequence'));});
test('deployed browser scripts exactly match tested source, independent of bundler symbol renaming',async()=>{const core=await(await app.fetch(new Request('https://test/lab/mark-comparison-core.js'),{},{})).text(),client=await(await app.fetch(new Request('https://test/lab/mark-comparison-client.js'),{},{})).text();assert.equal(core,await readFile(new URL('../src/mark-comparison-core-v3.41.0.js',import.meta.url),'utf8'));assert.equal(client,(await readFile(new URL('../src/mark-comparison-client-v3.41.0.js',import.meta.url),'utf8')).replace("'./mark-comparison-core-v3.41.0.js'","'/lab/mark-comparison-core.js'")+'\ninitComparison({document});\n');});
function fakePage(){const nodes=new Map(),selects=[{dataset:{horse:'エース'},value:''},{dataset:{horse:'スター'},value:''}];const node=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:'',value:'',disabled:false,listeners:{},addEventListener(k,f){this.listeners[k]=f;},querySelectorAll(){return selects;}});return nodes.get(id)};node('comparisonTarget').textContent=JSON.stringify({date:'2026-10-10',venue:'東京',raceNo:11,names:['エース','スター']});return{nodes,selects,document:{getElementById:node},storage:{getItem(){return null},setItem(){}}};}
test('rapid mark changes share one DB read and only the latest comparison is rendered',async()=>{const p=fakePage();let calls=0,resolve;const fetcher=()=>{calls++;return new Promise(r=>resolve=r)};const c=initComparison({...p,fetcher});p.selects[0].value='◎';const first=c.compare();await Promise.resolve();await Promise.resolve();p.selects[0].value='△';const second=c.compare();resolve({ok:true,json:async()=>({...fixture(),ok:true})});await Promise.all([first,second]);assert.equal(calls,1);assert(p.nodes.get('results').innerHTML.includes('△ エース'));assert(p.nodes.get('results').innerHTML.includes('印とDBの見方が近い'));p.selects[0].value='◎';await c.compare();assert.equal(calls,1);assert(p.nodes.get('results').innerHTML.includes('別の見方も確認'));p.selects[0].value='';await c.compare();assert.equal(calls,1);assert.equal(p.nodes.get('results').innerHTML,'');});
test('track change refreshes the DB; a failed refresh clears stale scores',async()=>{const p=fakePage();let calls=0;const c=initComparison({...p,fetcher:async()=>{calls++;if(calls===2)return{ok:false,json:async()=>({ok:false,error:'DB確認を保留'})};return{ok:true,json:async()=>({...fixture(),ok:true})};}});p.selects[0].value='◎';await c.compare();p.nodes.get('trackScenario').value='重';await c.compare();assert.equal(calls,2);assert.equal(p.nodes.get('results').innerHTML,'');assert.equal(p.nodes.get('baselineNote').textContent,'');assert(p.nodes.get('status').textContent.includes('DB確認を保留'));});
