import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {MEMO_KEY,MEMO_FIELDS,createMemo,parseMemoStore,storeMemo,upcomingWatch,composeReviewArticle,priorHumanMarks} from '../src/review-note-core-v3.43.0.js';
import {initReviewNote,initWatchNotes} from '../src/review-note-client-v3.43.0.js';
import {reviewNotePage} from '../src/review-note-page-v3.43.0.js';import app from '../src/index-v3.43.0.js';
const target={date:'2026-10-04',venue:'京都',raceNo:11,raceName:'テスト',names:['エース','スター']},stamp=Date.parse('2026-10-06T09:00:00Z');
const fields=()=>Object.fromEntries(Object.keys(MEMO_FIELDS).map(k=>[k,'']));
const history=()=>({ok:true,race:{...target},result:{complete:true},runners:[{horseName:'エース',horseNo:1,finishPosition:4,time:'1:45.0',last3f:34.5,cornerPositions:'3-3'},{horseName:'スター',horseNo:2,finishPosition:null,finishStatus:'中止',last3f:null,cornerPositions:null}],markRevisions:[],laboPrediction:{available:false}});
test('local memo snapshots validate inputs, preserve observations and never award accuracy credit',()=>{const f={...fields(),axis:'  前で運べた  '},watch=[{horseName:'エース',note:'次走確認'}];const m=createMemo(target,f,watch,stamp);f.axis='changed';watch[0].note='changed';assert.equal(m.fields.axis,'前で運べた');assert.equal(m.watch[0].note,'次走確認');assert.equal(m.eligibleForAccuracyEvaluation,false);assert.equal(parseMemoStore(JSON.stringify(storeMemo({},m)))[m.raceKey].fields.axis,'前で運べた');assert.throws(()=>createMemo(target,fields(),[]),/入力/);assert.throws(()=>createMemo(target,fields(),[{horseName:'別馬',note:'注目'}]),/対象馬/);assert.throws(()=>createMemo(target,{...fields(),axis:'a'.repeat(2001)},[]),/長さ/);assert.throws(()=>parseMemoStore('{bad'),/上書きせず/);});
test('memo store merges races without mutating previous entries and rejects new entries at capacity',()=>{const m=createMemo(target,{...fields(),overview:'メモ'},[],stamp),registry=Object.fromEntries(Array.from({length:100},(_,i)=>['old'+i,m]));assert.throws(()=>storeMemo(registry,m),/上限/);const original={one:m},next=storeMemo(original,{...m,raceKey:'two'});assert.equal(Object.keys(original).length,1);assert.equal(Object.keys(next).length,2);});
test('next-start watch matches names and excludes same/future races and notes saved after target cutoff',()=>{const m=createMemo(target,fields(),[{horseName:'エース',note:'馬場再確認'}],stamp),registry={[m.raceKey]:m};assert.equal(upcomingWatch(registry,{...target,date:'2026-10-10'}).length,1);assert.equal(upcomingWatch(registry,{...target,date:'2026-10-04'}).length,0);assert.equal(upcomingWatch(registry,{...target,date:'2026-10-06'}).length,0);assert.equal(upcomingWatch(registry,{...target,date:'2026-10-10',names:['別馬']}).length,0);assert.equal(upcomingWatch(registry,{...target,date:'2026-10-10'})[0].manualObservation,true);});
test('article includes full results and last3f/corners, keeps missing fields/statuses and separates manual review',()=>{const h=history(),before=JSON.stringify(h),m=createMemo(target,{...fields(),axis:'位置取りを再確認'},[{horseName:'スター',note:'次走の状態確認'}],stamp),text=composeReviewArticle(h,m);assert(text.includes('4着 1番 エース｜時計 1:45.0｜通過 3-3｜上がり3F 34.5秒'));assert(text.includes('中止 2番 スター'));assert(text.includes('上がり3F 未取得'));assert(text.includes('位置取りを再確認'));assert(text.includes('次走の状態確認'));assert(text.includes('確認できる事前LOCK記録なし'));assert.equal(JSON.stringify(h),before);});
test('same-day/post-race human marks and unverified LOCKs cannot become pre-race marks in articles',()=>{const h=history();h.markRevisions=[{createdAt:'2026-10-03T13:00:00Z',marked:[{horseName:'エース',horseNo:1,mark:'◎'}]},{createdAt:'2026-10-03T15:00:00Z',marked:[{horseName:'スター',mark:'◎'}]}];assert.equal(priorHumanMarks(h).marked[0].horseName,'エース');const text=composeReviewArticle(h);assert(text.includes('◎ 1番 エース'));assert(text.includes('◎ エース → 4着'));assert(!text.includes('◎ スター'));h.laboPrediction={available:true,locked:true,hashVerified:false,top5:[{horseName:'スター',mark:'○'}]};assert(!composeReviewArticle(h).includes('○'));h.markRevisions=[];h.laboPrediction.hashVerified=true;assert(composeReviewArticle(h).includes('○'));});
function fakePage(store=new Map()){const nodes=new Map(),watch=target.names.map(horse=>({dataset:{horse},value:'',addEventListener(){}}));const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',disabled:false,listeners:{},addEventListener(k,f){this.listeners[k]=f;},focus(){},select(){}});return nodes.get(id);};node('reviewTarget').textContent=JSON.stringify(target);return{nodes,watch,store,document:{getElementById:node,querySelectorAll:s=>s==='.watch-note'?watch:[...Object.keys(MEMO_FIELDS).map(k=>node('memo-'+k)),...watch]},storage:store===null?null:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}};}
test('editor saves and restores local memos, updates article immediately and copies exact plain text',async()=>{const p=fakePage();let copied;const c=initReviewNote({...p,now:()=>stamp,fetcher:async()=>({ok:true,json:async()=>history()}),clipboard:{writeText:async v=>copied=v}});await c.ready;p.nodes.get('memo-axis').value='ゲートを確認';p.watch[0].value='次走の馬場確認';c.edited();assert(p.nodes.get('articleText').value.includes('ゲートを確認'));assert(p.nodes.get('draftStatus').textContent.includes('未保存'));c.saveMemo();assert(p.nodes.get('memoStatus').textContent.includes('保存しました'));await c.copyText();assert.equal(copied,p.nodes.get('articleText').value);const p2=fakePage(p.store),c2=initReviewNote({...p2,fetcher:async()=>({ok:true,json:async()=>history()})});await c2.ready;assert.equal(p2.nodes.get('memo-axis').value,'ゲートを確認');assert.equal(p2.watch[0].value,'次走の馬場確認');});
test('corrupt/unavailable storage and quota failure protect data while article composition remains available',async()=>{for(const store of [null,new Map([[MEMO_KEY,'{bad']])]){const p=fakePage(store),c=initReviewNote({...p,fetcher:async()=>({ok:true,json:async()=>history()})});await c.ready;assert.equal(p.nodes.get('saveMemo').disabled,true);assert.equal(p.nodes.get('copyArticle').disabled,false);c.saveMemo();if(store)assert.equal(store.get(MEMO_KEY),'{bad');}const p=fakePage(),c=initReviewNote({...p,fetcher:async()=>({ok:true,json:async()=>history()})});await c.ready;p.nodes.get('memo-axis').value='入力';p.storage.setItem=()=>{throw Error('quota');};c.saveMemo();assert(p.nodes.get('memoStatus').textContent.includes('保存できません'));assert.equal(p.store.size,0);});
test('saving re-reads latest registry to retain another race written in another tab',async()=>{const p=fakePage(),c=initReviewNote({...p,fetcher:async()=>({ok:true,json:async()=>history()})});await c.ready;const other=createMemo({...target,raceNo:1},{...fields(),overview:'別レース'},[],stamp);p.store.set(MEMO_KEY,JSON.stringify({[other.raceKey]:other}));p.nodes.get('memo-overview').value='今のレース';c.saveMemo();assert.equal(Object.keys(JSON.parse(p.store.get(MEMO_KEY))).length,2);});
test('failed result fetch never copies a fabricated article and next-start observations render as text',async()=>{const p=fakePage(),c=initReviewNote({...p,fetcher:async()=>({ok:false,json:async()=>({ok:false,error:'保留'})})});await c.ready;assert.equal(p.nodes.get('copyArticle').disabled,true);assert.equal(p.nodes.get('articleText').value,'');const m=createMemo(target,fields(),[{horseName:'エース',note:'<script>観察</script>'}],stamp);const node={textContent:''};initWatchNotes({document:{getElementById:id=>id==='watchNotes'?node:{textContent:JSON.stringify({...target,date:'2026-10-10'})}},storage:{getItem:()=>JSON.stringify({[m.raceKey]:m})}});assert(node.textContent.includes('<script>観察</script>'));assert(node.textContent.includes('指数への反映なし'));});
test('browser sources match tested modules and review/watch entry points do not conflict',async()=>{const core=await(await app.fetch(new Request('https://test/lab/review-note-core.js'),{},{})).text(),client=await(await app.fetch(new Request('https://test/lab/review-note-client.js'),{},{})).text();assert.equal(core,await readFile(new URL('../src/review-note-core-v3.43.0.js',import.meta.url),'utf8'));assert.equal(client,(await readFile(new URL('../src/review-note-client-v3.43.0.js',import.meta.url),'utf8')).replace("'./review-note-core-v3.43.0.js'","'/lab/review-note-core.js'")+"\nif(document.getElementById('reviewTarget'))initReviewNote({document});\n");new Function(core.replaceAll('export ',''));new Function(client.replace(/^import[^;]+;\n/gm,'').replaceAll('export ',''));const p=await(await app.fetch(new Request('https://test/lab/expected-preview'),{},{})).text();assert(p.includes('/lab/note-review?'));assert(p.includes('id="watchNotes"'));assert(p.indexOf('id="watchNotes"')<p.indexOf('id="previewForm"'));assert(p.includes('mark-comparison-client.js'));assert(reviewNotePage({...target,names:['</script>危険']}).includes('\\u003c/script>'));});
test('review page and article API connect to stored card/results using read-only queries',async()=>{const race={race_key:'2026-10-04:京都:11',race_date:target.date,venue:target.venue,race_no:11,race_name:'テスト',runner_count:2,surface:'芝',distance:1800};const runners=[{horse_no:1,frame_no:1,horse_name:'エース',finish_position:4,finish_status:'完走',last3f:34.5,corner_positions:'3-3',time_text:'1:45.0'},{horse_no:2,frame_no:2,horse_name:'スター',finish_position:null,finish_status:'中止'}];let reads=0;const db={prepare(q){assert(q.startsWith('SELECT'));reads++;return{bind(){return this;},async first(){return q.includes('FROM jra_races')?race:null;},async all(){return{results:q.includes('FROM jra_runners')?runners:[]};}};}};const url='https://test/lab/note-review?date=2026-10-04&venue=京都&race_no=11',page=await app.fetch(new Request(url),{DB:db},{});assert((await page.text()).includes('エースの次走注目メモ'));const res=await app.fetch(new Request(url.replace('/lab/note-review','/v1/lab/note-review')),{DB:db},{}),d=await res.json();assert.equal(res.status,200);assert(d.text.includes('上がり3F 34.5秒'));assert(d.text.includes('中止 2番 スター'));assert.equal(d.memoStorage,'browser-local');assert(reads<12);});
