import{test}from'node:test';import assert from'node:assert/strict';import{DatabaseSync}from'node:sqlite';
import{executeCollection,schedulerStatus,summarize}from'../src/scheduler-observability.js';
import{runScheduled}from'../src/index-v3.7.1.js';import worker from'../src/index-v3.7.2.js';
function database(){const sqlite=new DatabaseSync(':memory:');const db={prepare(sql){const statement=args=>({run:async()=>sqlite.prepare(sql).run(...args),first:async()=>sqlite.prepare(sql).get(...args)||null,all:async()=>({results:sqlite.prepare(sql).all(...args)})});return{...statement([]),bind(...args){return statement(args);}};}};return{sqlite,db};}
const time=new Date('2026-10-05T06:00:00Z'),event={scheduledTime:time.getTime(),cron:'0 * * * *'},now=()=>time;
const success={runs:[{attempted:1,storedRaceCards:1,storedRunners:17,runs:[{status:'saved'}],discoveryErrors:[]}]};
test('missing cards are distinguished from source errors and never called unpublished',()=>{const missing={runs:[{attempted:1,runs:[{status:'card-not-discovered'}]}]};assert.equal(summarize(missing).status,'cards-not-discovered');assert.equal(summarize({runs:[{...missing.runs[0],discoveryErrors:[{status:503}]}]}).status,'error');assert.equal(summarize(success).status,'success');});
test('scheduled collection persists counts and a distinct cron heartbeat',async()=>{const{db}=database();const r=await executeCollection(event,{DB:db},{},{now,run:async()=>success});assert.equal(r.savedRunners,17);const status=await schedulerStatus(db,{now:time});assert.equal(status.cronHeartbeat,'observed');assert.equal(status.latestScheduled.saved_runners,17);assert.equal(status.latestScheduled.status,'success');});
test('duplicate scheduled delivery does not repeat ingestion',async()=>{const{db}=database();let count=0;const options={now,run:async()=>{count++;return success;}};await executeCollection(event,{DB:db},{},options);const second=await executeCollection(event,{DB:db},{},options);assert.equal(count,1);assert.ok(second.idempotent);});
test('manual collection cannot be mistaken for a working cron',async()=>{const{db}=database();await executeCollection(event,{DB:db},{},{trigger:'manual',now,run:async()=>success});const s=await schedulerStatus(db,{now:time});assert.equal(s.cronHeartbeat,'not-observed');assert.equal(s.runs[0].trigger_kind,'manual');});
test('pipeline exception is persisted and propagated',async()=>{const{db}=database();await assert.rejects(executeCollection(event,{DB:db},{},{now,run:async()=>{throw Error('source unavailable');}}));const s=await schedulerStatus(db,{now:time});assert.equal(s.latestScheduled.status,'error');assert.match(s.latestScheduled.error,/source unavailable/);});
test('missing scheduled heartbeat is marked overdue',async()=>{const{db}=database();await executeCollection(event,{DB:db},{},{now,run:async()=>success});assert.equal((await schedulerStatus(db,{now:new Date(time.getTime()+91*60000)})).cronHeartbeat,'overdue');});
test('failed staging stops collection instead of reporting success on stale programs',async()=>{let ingested=false;await assert.rejects(runScheduled(event,{DB:{}},{},{today:()=> '2026-10-05',stage:async()=>new Response(JSON.stringify({ok:false,error:'parser failure'})),ingest:async()=>{ingested=true;}}),/Program staging failed/);assert.equal(ingested,false);});
test('manual scheduler endpoint refuses GET without invoking DB',async()=>{const r=await worker.fetch(new Request('https://test/v1/lab/scheduler-run'),{},{});assert.equal(r.status,405);});
test('scheduler status rejects an unbounded history request',async()=>{const r=await worker.fetch(new Request('https://test/v1/lab/scheduler-status?limit=500'),{},{});assert.equal(r.status,400);});
