import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {Script} from 'node:vm';
import {runSourceCoordinator,pickSourceJob,SOURCE_CRON,LEGACY_SOURCE_CRONS} from '../src/source-coordinator-v3.40.0.js';import {pipelineStatus,pipelineHeartbeat} from '../src/pipeline-runs-v3.40.0.js';import {archivePage} from '../src/archive-page-v3.40.0.js';
function fixture(){const sql=new DatabaseSync(':memory:');const db={prepare(q){const wrap=(args=[])=>({bind(...a){return wrap(a)},async first(){return sql.prepare(q).get(...args)||null},async all(){return{results:sql.prepare(q).all(...args)}},async run(){const result=sql.prepare(q).run(...args);return{meta:{changes:Number(result.changes)}}}});return wrap()}};return{db,sql}}
const start=Date.parse('2026-10-06T08:00:00Z');
test('known legacy timer rotates every official collection stage, one source job per event',async()=>{const {db,sql}=fixture();let stamp=start;const calls=[],jobs=Object.fromEntries(['archive','results','history'].map(j=>[j,async()=>{calls.push(j);return{ok:true,status:'collected',externalRequests:1}}]));for(let i=0;i<6;i++){const r=await runSourceCoordinator({cron:'5,15,25,35,45,55 * * * *',scheduledTime:stamp},{DB:db},{now:()=>stamp,jobs});assert.equal(r.externalRequests,1);stamp+=600000}assert.deepEqual(calls,['archive','results','history','archive','results','history']);const status=await pipelineStatus(db,stamp);assert.ok(status.jobs.filter(x=>x.job!=='learning').every(x=>x.heartbeat==='observed'));assert.equal(status.jobs.find(x=>x.job==='learning').heartbeat,'not-observed');sql.close()});
test('duplicate delivery cannot choose a different job and repeat a source fetch',async()=>{const {db,sql}=fixture();const calls=[],jobs=Object.fromEntries(['archive','results','history'].map(j=>[j,async()=>{calls.push(j);return{ok:true,status:'collected',externalRequests:1}}]));const event={cron:SOURCE_CRON,scheduledTime:start};await runSourceCoordinator(event,{DB:db},{now:()=>start,jobs});assert.equal((await runSourceCoordinator(event,{DB:db},{now:()=>start,jobs})).status,'already-recorded');assert.deepEqual(calls,['archive']);assert.equal(sql.prepare('SELECT COUNT(*) n FROM lab_bounded_pipeline_runs').get().n,1);sql.close()});
test('manual progress is used for fair work rotation without claiming cron execution',async()=>{const {db,sql}=fixture();let stamp=start;const jobs=Object.fromEntries(['archive','results','history'].map(j=>[j,async()=>({ok:true,status:'collected',externalRequests:1})]));await runSourceCoordinator({cron:'manual',scheduledTime:stamp},{DB:db},{trigger:'manual',now:()=>stamp,jobs});assert.equal(await pickSourceJob(db),'results');const status=await pipelineStatus(db,stamp);assert.equal(status.jobs[0].heartbeat,'not-observed');stamp+=180000;assert.equal((await runSourceCoordinator({cron:SOURCE_CRON,scheduledTime:stamp},{DB:db},{now:()=>stamp,jobs})).dispatch.job,'results');sql.close()});
test('returned source failures remain visible and do not monopolize the next event',async()=>{const {db,sql}=fixture();const jobs={archive:async()=>({ok:false,status:'failed',externalRequests:1,error:'JRA取得 HTTP 429'}),results:async()=>({ok:true,status:'cooldown',externalRequests:0}),history:async()=>({ok:true,status:'idle',externalRequests:0})};await runSourceCoordinator({cron:SOURCE_CRON,scheduledTime:start},{DB:db},{now:()=>start,jobs});const status=await pipelineStatus(db,start);assert.equal(status.jobs[0].scheduled.error,'JRA取得 HTTP 429');assert.equal(await pickSourceJob(db),'results');const next=await runSourceCoordinator({cron:SOURCE_CRON,scheduledTime:start+180000},{DB:db},{now:()=>start+180000,jobs});assert.equal(next.status,'cooldown');assert.equal(next.externalRequests,0);sql.close()});
test('source timer changes preserve recognized legacy routes and readable truthful progress',()=>{assert.ok(LEGACY_SOURCE_CRONS.includes('5,15,25,35,45,55 * * * *'));assert.equal(SOURCE_CRON,'*/3 * * * *');const page=archivePage();for(const [,script] of page.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Script(script);assert.ok(page.includes('取得間隔の待機'));assert.ok(page.includes('自動実行はまだ未確認'));assert.ok(page.includes('3分間隔の設定'));assert.ok(page.includes('最終状態'))});

test('stale starts are not presented as healthy running jobs',()=>{
 const run={started_at:start,status:'running'};assert.equal(pipelineHeartbeat(run,start+60000),'running');assert.equal(pipelineHeartbeat(run,start+6*60000),'completion-unconfirmed');assert.equal(pipelineHeartbeat(run,start+31*60000),'overdue');assert.equal(pipelineHeartbeat({...run,status:'cooldown',finished_at:start+2000},start+60000),'observed');
});
