import {extractLinks,metaFromRacecardUrl,parseRace} from './index-v1.1.4.js';
import {persistFullDay} from './index.js';
import {inspectSourceCard,ensureEvidenceTable,sha256,runnerFingerprint} from './card-evidence.js';
import {ensureCollectionTables,officialUrl,jstDay} from './history-collection-v3.37.0.js';
import {parseArchiveProgram} from './archive-program-parser-v3.38.0.js';
export const ARCHIVE_POLICY={pagesPerBatch:1,cardsPerBatch:1,datesPerRequest:2,fromDate:'2016-01-01',globalLease:'jra-history',minPageGapMs:5000,minBatchGapMs:60000,errorPauseMs:3600000,publishedLinksOnly:true,pastDatesOnly:true,accuracyCredit:false};
const validDate=date=>/^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(Date.parse(date+'T00:00:00Z'))&&new Date(date+'T00:00:00Z').toISOString().slice(0,10)===date;
export function archiveDate(date,now=Date.now()){if(!validDate(date)||date<ARCHIVE_POLICY.fromDate||date>=jstDay(now))throw Error('過去日を2016-01-01以降で指定してください。');return date}
export function archivePageUrl(value,date){const u=new URL(officialUrl(value));if(u.hostname!=='www.jra.go.jp')throw Error('JRA公式ページを指定してください。');const [y,m,d]=date.split('-');if(u.pathname===`/keiba/calendar${y}/${y}/${Number(m)}/${m}${d}.html`&&!u.search)return u.href;if(u.pathname!=='/JRADB/accessD.html'||!/^pw01d/.test(u.searchParams.get('CNAME')||''))throw Error('掲載された出馬表リンク以外は取得しません。');const meta=metaFromRacecardUrl(u.href);if(meta&&meta.date!==date)throw Error('リンクの対象日が一致しません。');const stamp=(u.searchParams.get('CNAME')||'').match(/(20\d{6})\//)?.[1];if(stamp&&stamp!==date.replaceAll('-',''))throw Error('開催日の違う選択リンクは使用できません。');return u.href}
export async function ensureArchive(db){await ensureCollectionTables(db);await ensureEvidenceTable(db);await db.prepare('CREATE TABLE IF NOT EXISTS lab_archive_collection_targets(date TEXT PRIMARY KEY,status TEXT NOT NULL,last_run_at INTEGER NOT NULL DEFAULT 0,next_run_at INTEGER NOT NULL DEFAULT 0,error TEXT)').run();await db.prepare('CREATE TABLE IF NOT EXISTS lab_archive_collection_pages(date TEXT NOT NULL,url TEXT NOT NULL,race_key TEXT,status TEXT NOT NULL,last_attempt_at INTEGER NOT NULL DEFAULT 0,next_attempt_at INTEGER NOT NULL DEFAULT 0,source_sha256 TEXT,error TEXT,PRIMARY KEY(date,url))').run();}
export async function enqueueArchive(db,dates,now=Date.now()){if(!Array.isArray(dates)||!dates.length||dates.length>2||new Set(dates).size!==dates.length)throw Error('過去日は1～2日、重複なしで指定してください。');dates.forEach(d=>archiveDate(d,now));await ensureArchive(db);for(const date of dates){const [y,m,d]=date.split('-'),url=`https://www.jra.go.jp/keiba/calendar${y}/${y}/${Number(m)}/${m}${d}.html`;await db.prepare("INSERT OR IGNORE INTO lab_archive_collection_targets(date,status) VALUES(?,'pending')").bind(date).run();await db.prepare("INSERT OR IGNORE INTO lab_archive_collection_pages(date,url,status) VALUES(?,?,'pending')").bind(date,url).run()}return{ok:true,dates,externalRequests:0,policy:ARCHIVE_POLICY}}
export function archiveLinks(html,base,date){const out=[];for(const url of extractLinks(html,base)){try{archivePageUrl(url,date);if(new URL(url).pathname==='/JRADB/accessD.html')out.push(url)}catch{}}return [...new Set(out)].slice(0,60)}
function validateParsedCard(race,evidence){return race.runnerCount>=1&&race.runnerCount<=18&&race.runners.length===race.runnerCount&&new Set(race.runners.map(x=>x.name)).size===race.runnerCount&&race.runners.every((r,i)=>r.name&&r.horseNo===i+1&&Number.isInteger(r.age)&&r.age>=2&&r.age<=20)&&evidence.sourceRowCount===race.runnerCount&&evidence.allHorseNumbersObserved&&evidence.allFramesObserved&&(evidence.declaredCount==null||evidence.declaredCount===race.runnerCount)&&['芝','ダート','障害','障害芝','障害ダート','芝・ダート'].includes(race.surface)&&race.distance>0}
export async function collectArchiveBatch(db,deps={}){
 const now=deps.now||Date.now,fetcher=deps.fetcher||fetch,wait=deps.wait||(ms=>new Promise(r=>setTimeout(r,ms))),parse=deps.parseRace||parseRace,inspect=deps.inspectSourceCard||inspectSourceCard,persist=deps.persistFullDay||persistFullDay;
 await ensureArchive(db);const target=await db.prepare("SELECT * FROM lab_archive_collection_targets WHERE status<>'complete' AND next_run_at<=? ORDER BY last_run_at,date LIMIT 1").bind(now()).first();if(!target)return{ok:true,status:'idle',externalRequests:0,policy:ARCHIVE_POLICY};archiveDate(target.date,now());
 const stamp=now(),token=crypto.randomUUID(),claim=await db.prepare("UPDATE lab_history_collection_budget SET locked_until=?,lock_token=? WHERE name='jra-history' AND locked_until<=? AND next_batch_at<=?").bind(stamp+120000,token,stamp,stamp).run();if(Number(claim.meta?.changes||0)!==1)return{ok:true,status:'cooldown',externalRequests:0,policy:ARCHIVE_POLICY};
 let requests=0,cooldown=60000,savedCards=0,error=null;const runs=[];
 try{for(let step=0;step<1;step++){
  const page=await db.prepare("SELECT * FROM lab_archive_collection_pages WHERE date=? AND status<>'complete' AND next_attempt_at<=? ORDER BY last_attempt_at,CASE WHEN race_key IS NOT NULL THEN 0 ELSE 1 END,CASE WHEN instr(url,'pw01dde10')>0 THEN 0 ELSE 1 END,url LIMIT 1").bind(target.date,now()).first();if(!page)break;
  const meta=metaFromRacecardUrl(page.url);
  if(meta){const key=`${target.date}:${meta.venue}:${meta.raceNo}`,existing=await db.prepare('SELECT r.runner_count,(SELECT COUNT(*) FROM jra_runners rr WHERE rr.race_key=r.race_key) stored FROM jra_races r WHERE r.race_key=?').bind(key).first();if(existing&&Number(existing.runner_count)>0&&Number(existing.runner_count)===Number(existing.stored)){await db.prepare("UPDATE lab_archive_collection_pages SET status='complete',last_attempt_at=? WHERE date=? AND url=?").bind(now(),target.date,page.url).run();runs.push({status:'already-stored',raceKey:key});continue}}
  try{
   const url=archivePageUrl(page.url,target.date),u=new URL(url),action=u.pathname==='/JRADB/accessD.html';if(requests)await wait(5000);requests++;
   const response=await fetcher(action?u.origin+u.pathname:url,{method:action?'POST':'GET',body:action?new URLSearchParams({CNAME:u.searchParams.get('CNAME')}).toString():undefined,headers:{'user-agent':'KEIBA-LABO/3.38 bounded archive',accept:'text/html',...(action?{'content-type':'application/x-www-form-urlencoded'}:{})},redirect:'follow',signal:AbortSignal.timeout(10000)});
   if(!response.ok){if(response.status===429||response.status===503)cooldown=3600000;throw Error('JRA取得 HTTP '+response.status)}
   if(response.url){const resolved=new URL(response.url);officialUrl(resolved.href);if(action?(resolved.origin!==u.origin||resolved.pathname!==u.pathname):resolved.href!==url)throw Error('JRA取得先の対象ページが変わりました。')}
   const bytes=await response.arrayBuffer();if(bytes.byteLength>1500000)throw Error('ページサイズ上限を超えました。');const body=new TextDecoder(/charset\s*=\s*["']?utf-?8/i.test(response.headers.get('content-type')||'')?'utf-8':'shift_jis').decode(bytes),sha=await sha256(body);
   const links=archiveLinks(body,url,target.date).map(link=>{const m=metaFromRacecardUrl(link);return{url:link,raceKey:m?`${target.date}:${m.venue}:${m.raceNo}`:null}});
   if(links.length)await db.prepare("INSERT OR IGNORE INTO lab_archive_collection_pages(date,url,race_key,status) SELECT ?,json_extract(value,'$.url'),json_extract(value,'$.raceKey'),'pending' FROM json_each(?)").bind(target.date,JSON.stringify(links)).run();
   if(!action){const programs=parseArchiveProgram(body,target.date,url);if(!programs.length||programs.some(r=>r.date!==target.date)||new Set(programs.map(r=>r.programKey)).size!==programs.length)throw Error('開催番組を確認できません。');await db.prepare("INSERT INTO jra_race_program(program_key,race_date,venue,meeting_no,day_no,race_no,race_label,surface,distance,start_time,grade,source_url,fetched_at) SELECT json_extract(value,'$.programKey'),json_extract(value,'$.date'),json_extract(value,'$.venue'),json_extract(value,'$.meetingNo'),json_extract(value,'$.dayNo'),json_extract(value,'$.raceNo'),json_extract(value,'$.raceLabel'),json_extract(value,'$.surface'),json_extract(value,'$.distance'),json_extract(value,'$.startTime'),json_extract(value,'$.grade'),json_extract(value,'$.sourceUrl'),? FROM json_each(?) WHERE 1 ON CONFLICT(program_key) DO NOTHING").bind(new Date(now()).toISOString(),JSON.stringify(programs)).run();runs.push({status:'program-links-saved',programRaces:programs.length,links:links.length})}
   else if(meta){const program=await db.prepare('SELECT program_key FROM jra_race_program WHERE race_date=? AND venue=? AND race_no=?').bind(target.date,meta.venue,meta.raceNo).first();if(!program)throw Error('開催番組との一致を確認できません。');const race=parse({ok:true,status:response.status,url,body},target.date,meta.venue,meta.raceNo),evidence=inspect(body);if(!validateParsedCard(race,evidence))throw Error('出馬表の全馬・年齢・馬番・枠番を確認できません。');race.runners=race.runners.map(r=>({...r,frameNo:evidence.frames.get(r.horseNo)}));const result=await persist(db,{date:target.date,races:[race]});const key=program.program_key;if(!result.saved?.some(x=>x.raceKey===key&&x.status==='saved'))throw Error('出馬表の保存を確認できません。');await db.prepare('INSERT INTO lab_card_source_evidence(race_key,source_url,source_sha256,runner_sha256,declared_count,source_row_count,parsed_count,horse_numbers_observed,frames_observed,card_fetched_at,verified_at,count_basis) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(race_key) DO NOTHING').bind(key,url,sha,await sha256(runnerFingerprint(race.runners)),evidence.declaredCount,evidence.sourceRowCount,race.runnerCount,1,1,result.fetchedAt,new Date(now()).toISOString(),evidence.countBasis).run();await db.prepare("INSERT OR IGNORE INTO lab_history_collection_targets(race_key,date,venue,race_no,history_limit,status) VALUES(?,?,?,?,10,'pending')").bind(key,target.date,meta.venue,meta.raceNo).run();savedCards++;runs.push({status:'card-saved',raceKey:key,runnerCount:race.runnerCount,sourceSha256:sha})}
   else runs.push({status:'published-selector-links-saved',links:links.length});
   await db.prepare("UPDATE lab_archive_collection_pages SET status='complete',last_attempt_at=?,source_sha256=?,error=NULL WHERE date=? AND url=?").bind(now(),sha,target.date,page.url).run();if(savedCards)break;
  }catch(e){error=String(e.message||e);await db.prepare("UPDATE lab_archive_collection_pages SET status='failed',last_attempt_at=?,next_attempt_at=?,error=? WHERE date=? AND url=?").bind(now(),now()+3600000,error,target.date,page.url).run();runs.push({status:'deferred',url:page.url,error});if(cooldown===3600000)break}
 }
 const coverage=await db.prepare('SELECT COUNT(*) total,SUM(CASE WHEN r.runner_count>0 AND r.runner_count=(SELECT COUNT(*) FROM jra_runners rr WHERE rr.race_key=r.race_key) THEN 1 ELSE 0 END) complete FROM jra_race_program p LEFT JOIN jra_races r ON r.race_key=p.program_key WHERE p.race_date=?').bind(target.date).first(),pending=await db.prepare("SELECT COUNT(*) n FROM lab_archive_collection_pages WHERE date=? AND status<>'complete'").bind(target.date).first();const complete=Number(coverage?.total)>0&&Number(coverage.complete)===Number(coverage.total);const blocked=!complete&&!Number(pending?.n);await db.prepare('UPDATE lab_archive_collection_targets SET status=?,last_run_at=?,next_run_at=?,error=? WHERE date=?').bind(complete?'complete':blocked?'awaiting-published-card-links':'pending',now(),blocked?now()+86400000:0,blocked?'当日の正式出馬表リンクが未発見です。結果ページからのカード再構成は未対応です。':error,target.date).run();return{ok:!error,status:complete?'complete':blocked?'awaiting-published-card-links':savedCards?'collected':'discovered',date:target.date,externalRequests:requests,savedCards,coverage,runs,policy:ARCHIVE_POLICY};
 }finally{await db.prepare("UPDATE lab_history_collection_budget SET locked_until=0,next_batch_at=?,lock_token=NULL WHERE name='jra-history' AND lock_token=?").bind(now()+cooldown,token).run()}
}
export async function archiveStatus(db){let targets;try{targets=(await db.prepare('SELECT * FROM lab_archive_collection_targets ORDER BY date').all()).results||[]}catch(e){if(/no such table/.test(String(e)))return{ok:true,targets:[],policy:ARCHIVE_POLICY};throw e}const coverage=(await db.prepare('SELECT t.date,(SELECT COUNT(*) FROM jra_race_program p WHERE p.race_date=t.date) programRaces,(SELECT COUNT(*) FROM jra_races r WHERE r.race_date=t.date) storedCards,(SELECT COUNT(*) FROM jra_races r WHERE r.race_date=t.date AND r.runner_count>0 AND r.runner_count=(SELECT COUNT(*) FROM jra_runners rr WHERE rr.race_key=r.race_key)) completeCards FROM lab_archive_collection_targets t ORDER BY t.date').all()).results||[];const pages=(await db.prepare('SELECT date,status,COUNT(*) pages FROM lab_archive_collection_pages GROUP BY date,status').all()).results||[];return{ok:true,targets:targets.map(t=>({...t,lastRunAt:t.last_run_at?new Date(t.last_run_at).toISOString():null,nextRunAt:t.next_run_at?new Date(t.next_run_at).toISOString():null})),pages,coverage,policy:ARCHIVE_POLICY}}
