// Public five-start table verified 2026-10-07; rest/cancelled entries excluded.
export const IRELAND_HISTORY_SOURCE_URL='https://race.netkeiba.com/race/shutuba_past.html?race_id=202605040411';
export const IRELAND_HISTORY_OBSERVED_AT='2026-10-07';
export const IRELAND_HISTORY_ROWS=[
 {
  "horse_name": "ウイントワイライト",
  "race_date": "2026-06-21",
  "venue": "東京",
  "race_name": "府中牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 2,
  "field_size": 16,
  "time_text": "1:46.0",
  "last3f": 33.9,
  "corner_positions": "13-13-13",
  "track_condition": "稍"
 },
 {
  "horse_name": "ウイントワイライト",
  "race_date": "2026-05-02",
  "venue": "東京",
  "race_name": "京王杯SC",
  "surface": "芝",
  "distance": 1400,
  "finish_position": 16,
  "field_size": 18,
  "time_text": "1:19.8",
  "last3f": 32.1,
  "corner_positions": "18-18",
  "track_condition": "良"
 },
 {
  "horse_name": "ウイントワイライト",
  "race_date": "2026-03-22",
  "venue": "中京",
  "race_name": "愛知杯",
  "surface": "芝",
  "distance": 1400,
  "finish_position": 7,
  "field_size": 18,
  "time_text": "1:19.9",
  "last3f": 33.1,
  "corner_positions": "15-15",
  "track_condition": "良"
 },
 {
  "horse_name": "ウイントワイライト",
  "race_date": "2026-02-01",
  "venue": "東京",
  "race_name": "節分S",
  "surface": "芝",
  "distance": 1400,
  "finish_position": 1,
  "field_size": 15,
  "time_text": "1:21.0",
  "last3f": 33.1,
  "corner_positions": "9-10",
  "track_condition": "良"
 },
 {
  "horse_name": "ヴォンフレ",
  "race_date": "2026-08-08",
  "venue": "新潟",
  "race_name": "関越S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 5,
  "field_size": 16,
  "time_text": "1:45.3",
  "last3f": 32.7,
  "corner_positions": "4-3",
  "track_condition": "良"
 },
 {
  "horse_name": "ヴォンフレ",
  "race_date": "2026-07-18",
  "venue": "福島",
  "race_name": "阿武隈S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 6,
  "field_size": 16,
  "time_text": "1:46.6",
  "last3f": 34.9,
  "corner_positions": "12-12-11-10",
  "track_condition": "良"
 },
 {
  "horse_name": "ヴォンフレ",
  "race_date": "2026-05-16",
  "venue": "東京",
  "race_name": "調布特別",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 1,
  "field_size": 9,
  "time_text": "1:46.0",
  "last3f": 33.1,
  "corner_positions": "1-1-2",
  "track_condition": "良"
 },
 {
  "horse_name": "ヴォンフレ",
  "race_date": "2026-05-02",
  "venue": "新潟",
  "race_name": "胎内川特別",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 7,
  "field_size": 15,
  "time_text": "1:48.0",
  "last3f": 35,
  "corner_positions": "5-5",
  "track_condition": "稍"
 },
 {
  "horse_name": "ヴォンフレ",
  "race_date": "2026-03-22",
  "venue": "中山",
  "race_name": "4歳以上2勝クラス",
  "surface": "ダート",
  "distance": 1800,
  "finish_position": 9,
  "field_size": 16,
  "time_text": "1:55.0",
  "last3f": 40.3,
  "corner_positions": "12-10-5-4",
  "track_condition": "良"
 },
 {
  "horse_name": "カネラフィーナ",
  "race_date": "2026-08-16",
  "venue": "中京",
  "race_name": "中京記念",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 8,
  "field_size": 16,
  "time_text": "1:31.6",
  "last3f": 33.8,
  "corner_positions": "4-7-8",
  "track_condition": "良"
 },
 {
  "horse_name": "カネラフィーナ",
  "race_date": "2026-06-13",
  "venue": "東京",
  "race_name": "ジューンS",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 1,
  "field_size": 13,
  "time_text": "1:46.0",
  "last3f": 33.8,
  "corner_positions": "3-3-3",
  "track_condition": "良"
 },
 {
  "horse_name": "カネラフィーナ",
  "race_date": "2026-04-19",
  "venue": "福島",
  "race_name": "福島牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 7,
  "field_size": 16,
  "time_text": "1:46.0",
  "last3f": 34.8,
  "corner_positions": "6-6-5-4",
  "track_condition": "良"
 },
 {
  "horse_name": "カネラフィーナ",
  "race_date": "2026-01-04",
  "venue": "中山",
  "race_name": "日刊中山金",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 4,
  "field_size": 14,
  "time_text": "2:00.6",
  "last3f": 34.2,
  "corner_positions": "8-9-9-9",
  "track_condition": "良"
 },
 {
  "horse_name": "カネラフィーナ",
  "race_date": "2025-10-19",
  "venue": "新潟",
  "race_name": "新潟牝馬S",
  "surface": "芝",
  "distance": 2200,
  "finish_position": 1,
  "field_size": 14,
  "time_text": "2:12.7",
  "last3f": 34.6,
  "corner_positions": "4-4-5-4",
  "track_condition": "良"
 },
 {
  "horse_name": "カムニャック",
  "race_date": "2026-05-17",
  "venue": "東京",
  "race_name": "ヴィクトリ",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 2,
  "field_size": 18,
  "time_text": "1:31.1",
  "last3f": 33.1,
  "corner_positions": "7-7",
  "track_condition": "良"
 },
 {
  "horse_name": "カムニャック",
  "race_date": "2026-04-11",
  "venue": "阪神",
  "race_name": "阪神牝馬S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 2,
  "field_size": 10,
  "time_text": "1:31.6",
  "last3f": 33.2,
  "corner_positions": "4-3",
  "track_condition": "良"
 },
 {
  "horse_name": "カムニャック",
  "race_date": "2025-10-19",
  "venue": "京都",
  "race_name": "秋華賞",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 16,
  "field_size": 18,
  "time_text": "2:00.2",
  "last3f": 36.9,
  "corner_positions": "3-4-3-3",
  "track_condition": "良"
 },
 {
  "horse_name": "カムニャック",
  "race_date": "2025-09-14",
  "venue": "阪神",
  "race_name": "ローズS",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 1,
  "field_size": 17,
  "time_text": "1:43.5",
  "last3f": 34.4,
  "corner_positions": "6-7",
  "track_condition": "良"
 },
 {
  "horse_name": "クイーンズウォーク",
  "race_date": "2026-05-17",
  "venue": "東京",
  "race_name": "ヴィクトリ",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 3,
  "field_size": 18,
  "time_text": "1:31.4",
  "last3f": 33.1,
  "corner_positions": "8-10",
  "track_condition": "良"
 },
 {
  "horse_name": "クイーンズウォーク",
  "race_date": "2026-03-15",
  "venue": "中京",
  "race_name": "金鯱賞",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 3,
  "field_size": 14,
  "time_text": "1:58.2",
  "last3f": 34.1,
  "corner_positions": "5-5-6-6",
  "track_condition": "良"
 },
 {
  "horse_name": "クイーンズウォーク",
  "race_date": "2025-11-02",
  "venue": "東京",
  "race_name": "天皇賞(秋",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 9,
  "field_size": 14,
  "time_text": "1:59.0",
  "last3f": 32.8,
  "corner_positions": "7-6-6",
  "track_condition": "良"
 },
 {
  "horse_name": "クランフォード",
  "race_date": "2026-09-05",
  "venue": "中山",
  "race_name": "京成杯AH",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 7,
  "field_size": 16,
  "time_text": "1:32.6",
  "last3f": 34.8,
  "corner_positions": "2-2-2",
  "track_condition": "良"
 },
 {
  "horse_name": "クランフォード",
  "race_date": "2026-07-26",
  "venue": "新潟",
  "race_name": "関屋記念",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 2,
  "field_size": 14,
  "time_text": "1:33.3",
  "last3f": 35.2,
  "corner_positions": "1-1",
  "track_condition": "不"
 },
 {
  "horse_name": "クランフォード",
  "race_date": "2026-05-10",
  "venue": "新潟",
  "race_name": "谷川岳S",
  "surface": "芝",
  "distance": 1400,
  "finish_position": 11,
  "field_size": 14,
  "time_text": "1:21.9",
  "last3f": 35.6,
  "corner_positions": "4-5",
  "track_condition": "良"
 },
 {
  "horse_name": "クランフォード",
  "race_date": "2026-04-11",
  "venue": "阪神",
  "race_name": "阪神牝馬S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 4,
  "field_size": 10,
  "time_text": "1:31.8",
  "last3f": 33.4,
  "corner_positions": "3-3",
  "track_condition": "良"
 },
 {
  "horse_name": "クランフォード",
  "race_date": "2026-03-29",
  "venue": "阪神",
  "race_name": "六甲S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 2,
  "field_size": 13,
  "time_text": "1:32.1",
  "last3f": 34.1,
  "corner_positions": "2-2",
  "track_condition": "良"
 },
 {
  "horse_name": "ジョスラン",
  "race_date": "2026-05-17",
  "venue": "東京",
  "race_name": "ヴィクトリ",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 8,
  "field_size": 18,
  "time_text": "1:31.6",
  "last3f": 33.5,
  "corner_positions": "8-9",
  "track_condition": "良"
 },
 {
  "horse_name": "ジョスラン",
  "race_date": "2026-01-24",
  "venue": "小倉",
  "race_name": "小倉牝馬S",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 1,
  "field_size": 18,
  "time_text": "1:58.1",
  "last3f": 33.9,
  "corner_positions": "7-9-6-6",
  "track_condition": "良"
 },
 {
  "horse_name": "ジョスラン",
  "race_date": "2025-10-19",
  "venue": "京都",
  "race_name": "秋華賞",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 4,
  "field_size": 18,
  "time_text": "1:58.8",
  "last3f": 34.7,
  "corner_positions": "6-9-11-13",
  "track_condition": "良"
 },
 {
  "horse_name": "ジョスラン",
  "race_date": "2025-09-07",
  "venue": "中山",
  "race_name": "紫苑S",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 2,
  "field_size": 13,
  "time_text": "1:59.1",
  "last3f": 33.6,
  "corner_positions": "5-5-4-5",
  "track_condition": "良"
 },
 {
  "horse_name": "セキトバイースト",
  "race_date": "2026-06-21",
  "venue": "東京",
  "race_name": "府中牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 1,
  "field_size": 16,
  "time_text": "1:45.5",
  "last3f": 35.1,
  "corner_positions": "1-1-1",
  "track_condition": "稍"
 },
 {
  "horse_name": "セキトバイースト",
  "race_date": "2026-05-16",
  "venue": "新潟",
  "race_name": "新潟大賞典",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 7,
  "field_size": 15,
  "time_text": "1:59.4",
  "last3f": 34.5,
  "corner_positions": "3-3",
  "track_condition": "良"
 },
 {
  "horse_name": "セキトバイースト",
  "race_date": "2026-03-15",
  "venue": "中京",
  "race_name": "金鯱賞",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 11,
  "field_size": 14,
  "time_text": "1:59.0",
  "last3f": 35.8,
  "corner_positions": "3-2-2-2",
  "track_condition": "良"
 },
 {
  "horse_name": "セキトバイースト",
  "race_date": "2025-11-16",
  "venue": "京都",
  "race_name": "エリザベス",
  "surface": "芝",
  "distance": 2200,
  "finish_position": 6,
  "field_size": 16,
  "time_text": "2:11.6",
  "last3f": 35.3,
  "corner_positions": "4-4-3-3",
  "track_condition": "良"
 },
 {
  "horse_name": "チェルビアット",
  "race_date": "2026-08-16",
  "venue": "中京",
  "race_name": "中京記念",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 7,
  "field_size": 16,
  "time_text": "1:31.6",
  "last3f": 34.2,
  "corner_positions": "4-5-5",
  "track_condition": "良"
 },
 {
  "horse_name": "チェルビアット",
  "race_date": "2026-05-24",
  "venue": "京都",
  "race_name": "都大路S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 2,
  "field_size": 13,
  "time_text": "1:43.7",
  "last3f": 34.3,
  "corner_positions": "7-8",
  "track_condition": "良"
 },
 {
  "horse_name": "チェルビアット",
  "race_date": "2026-03-22",
  "venue": "中京",
  "race_name": "愛知杯",
  "surface": "芝",
  "distance": 1400,
  "finish_position": 5,
  "field_size": 18,
  "time_text": "1:19.8",
  "last3f": 33.8,
  "corner_positions": "8-6",
  "track_condition": "良"
 },
 {
  "horse_name": "チェルビアット",
  "race_date": "2026-02-14",
  "venue": "京都",
  "race_name": "洛陽S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 2,
  "field_size": 14,
  "time_text": "1:34.2",
  "last3f": 33.5,
  "corner_positions": "3-3",
  "track_condition": "良"
 },
 {
  "horse_name": "チェルビアット",
  "race_date": "2025-12-20",
  "venue": "中山",
  "race_name": "ターコイズ",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 13,
  "field_size": 16,
  "time_text": "1:33.6",
  "last3f": 33.8,
  "corner_positions": "16-15-13",
  "track_condition": "良"
 },
 {
  "horse_name": "テリオスララ",
  "race_date": "2026-06-21",
  "venue": "東京",
  "race_name": "府中牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 16,
  "field_size": 16,
  "time_text": "1:50.9",
  "last3f": 39.7,
  "corner_positions": "2-2-2",
  "track_condition": "稍"
 },
 {
  "horse_name": "テリオスララ",
  "race_date": "2026-03-08",
  "venue": "阪神",
  "race_name": "大阪城S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 10,
  "field_size": 13,
  "time_text": "1:45.4",
  "last3f": 36.1,
  "corner_positions": "1-1",
  "track_condition": "良"
 },
 {
  "horse_name": "テリオスララ",
  "race_date": "2026-02-10",
  "venue": "東京",
  "race_name": "初音S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 1,
  "field_size": 11,
  "time_text": "1:45.7",
  "last3f": 33.2,
  "corner_positions": "1-1-1",
  "track_condition": "良"
 },
 {
  "horse_name": "テリオスララ",
  "race_date": "2025-10-19",
  "venue": "東京",
  "race_name": "甲斐路S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 10,
  "field_size": 18,
  "time_text": "1:46.4",
  "last3f": 34.3,
  "corner_positions": "5-5-7",
  "track_condition": "良"
 },
 {
  "horse_name": "ニシノティアモ",
  "race_date": "2026-06-21",
  "venue": "東京",
  "race_name": "府中牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 10,
  "field_size": 16,
  "time_text": "1:47.0",
  "last3f": 35.4,
  "corner_positions": "7-7-7",
  "track_condition": "稍"
 },
 {
  "horse_name": "ニシノティアモ",
  "race_date": "2026-05-17",
  "venue": "東京",
  "race_name": "ヴィクトリ",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 6,
  "field_size": 18,
  "time_text": "1:31.5",
  "last3f": 34.1,
  "corner_positions": "2-2",
  "track_condition": "良"
 },
 {
  "horse_name": "ニシノティアモ",
  "race_date": "2026-03-07",
  "venue": "中山",
  "race_name": "中山牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 5,
  "field_size": 16,
  "time_text": "1:47.3",
  "last3f": 35.1,
  "corner_positions": "10-12-10-9",
  "track_condition": "稍"
 },
 {
  "horse_name": "ニシノティアモ",
  "race_date": "2025-11-22",
  "venue": "福島",
  "race_name": "福島記念",
  "surface": "芝",
  "distance": 2000,
  "finish_position": 1,
  "field_size": 16,
  "time_text": "1:59.9",
  "last3f": 34,
  "corner_positions": "2-2-2-2",
  "track_condition": "良"
 },
 {
  "horse_name": "ハワイアンティアレ",
  "race_date": "2026-08-01",
  "venue": "中京",
  "race_name": "豊橋S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 1,
  "field_size": 11,
  "time_text": "1:33.1",
  "last3f": 33.1,
  "corner_positions": "1-1-1",
  "track_condition": "良"
 },
 {
  "horse_name": "ハワイアンティアレ",
  "race_date": "2026-05-17",
  "venue": "京都",
  "race_name": "錦S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 10,
  "field_size": 13,
  "time_text": "1:32.9",
  "last3f": 32.4,
  "corner_positions": "10-11",
  "track_condition": "良"
 },
 {
  "horse_name": "ハワイアンティアレ",
  "race_date": "2026-05-02",
  "venue": "新潟",
  "race_name": "三条S",
  "surface": "ダート",
  "distance": 1800,
  "finish_position": 8,
  "field_size": 15,
  "time_text": "1:54.8",
  "last3f": 39.6,
  "corner_positions": "9-8-8-10",
  "track_condition": "重"
 },
 {
  "horse_name": "ハワイアンティアレ",
  "race_date": "2026-03-01",
  "venue": "阪神",
  "race_name": "伊丹S",
  "surface": "ダート",
  "distance": 1800,
  "finish_position": 14,
  "field_size": 14,
  "time_text": "1:55.4",
  "last3f": 39.4,
  "corner_positions": "2-2-2-4",
  "track_condition": "良"
 },
 {
  "horse_name": "ハワイアンティアレ",
  "race_date": "2026-01-31",
  "venue": "京都",
  "race_name": "舞鶴S",
  "surface": "ダート",
  "distance": 1800,
  "finish_position": 4,
  "field_size": 13,
  "time_text": "1:52.9",
  "last3f": 37.5,
  "corner_positions": "9-9-7-7",
  "track_condition": "良"
 },
 {
  "horse_name": "ミアネーロ",
  "race_date": "2026-08-08",
  "venue": "新潟",
  "race_name": "関越S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 3,
  "field_size": 16,
  "time_text": "1:45.2",
  "last3f": 32.7,
  "corner_positions": "3-3",
  "track_condition": "良"
 },
 {
  "horse_name": "ミアネーロ",
  "race_date": "2026-06-21",
  "venue": "東京",
  "race_name": "府中牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 3,
  "field_size": 16,
  "time_text": "1:46.0",
  "last3f": 34.5,
  "corner_positions": "5-7-7",
  "track_condition": "稍"
 },
 {
  "horse_name": "ミアネーロ",
  "race_date": "2026-03-08",
  "venue": "中山",
  "race_name": "総武S",
  "surface": "ダート",
  "distance": 1800,
  "finish_position": 15,
  "field_size": 15,
  "time_text": "1:55.9",
  "last3f": 40.8,
  "corner_positions": "13-13-13-13",
  "track_condition": "稍"
 },
 {
  "horse_name": "ミアネーロ",
  "race_date": "2025-10-19",
  "venue": "新潟",
  "race_name": "新潟牝馬S",
  "surface": "芝",
  "distance": 2200,
  "finish_position": 4,
  "field_size": 14,
  "time_text": "2:13.1",
  "last3f": 34.6,
  "corner_positions": "11-11-8-7",
  "track_condition": "良"
 },
 {
  "horse_name": "ミアネーロ",
  "race_date": "2025-06-22",
  "venue": "東京",
  "race_name": "府中牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 11,
  "field_size": 14,
  "time_text": "1:46.9",
  "last3f": 35.4,
  "corner_positions": "8-10-10",
  "track_condition": "良"
 },
 {
  "horse_name": "ミラビリスマジック",
  "race_date": "2026-07-18",
  "venue": "福島",
  "race_name": "阿武隈S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 1,
  "field_size": 16,
  "time_text": "1:46.2",
  "last3f": 34.9,
  "corner_positions": "7-7-7-7",
  "track_condition": "良"
 },
 {
  "horse_name": "ミラビリスマジック",
  "race_date": "2026-05-17",
  "venue": "新潟",
  "race_name": "弥彦S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 5,
  "field_size": 16,
  "time_text": "1:49.3",
  "last3f": 33,
  "corner_positions": "5-5",
  "track_condition": "良"
 },
 {
  "horse_name": "ミラビリスマジック",
  "race_date": "2026-03-28",
  "venue": "中京",
  "race_name": "マレーシア",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 9,
  "field_size": 16,
  "time_text": "1:32.9",
  "last3f": 34.1,
  "corner_positions": "6-9-9",
  "track_condition": "良"
 },
 {
  "horse_name": "ミラビリスマジック",
  "race_date": "2026-02-15",
  "venue": "東京",
  "race_name": "雲雀S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 13,
  "field_size": 16,
  "time_text": "1:34.9",
  "last3f": 34,
  "corner_positions": "3-3",
  "track_condition": "良"
 },
 {
  "horse_name": "ミラビリスマジック",
  "race_date": "2025-05-10",
  "venue": "東京",
  "race_name": "分倍河原S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 8,
  "field_size": 15,
  "time_text": "1:35.0",
  "last3f": 33.6,
  "corner_positions": "5-5",
  "track_condition": "稍"
 },
 {
  "horse_name": "ムイ",
  "race_date": "2026-09-05",
  "venue": "阪神",
  "race_name": "エニフS",
  "surface": "ダート",
  "distance": 1400,
  "finish_position": 12,
  "field_size": 12,
  "time_text": "1:25.7",
  "last3f": 37.7,
  "corner_positions": "9-8",
  "track_condition": "稍"
 },
 {
  "horse_name": "ムイ",
  "race_date": "2026-05-31",
  "venue": "京都",
  "race_name": "安土城S",
  "surface": "芝",
  "distance": 1400,
  "finish_position": 15,
  "field_size": 17,
  "time_text": "1:21.3",
  "last3f": 33,
  "corner_positions": "14-14",
  "track_condition": "良"
 },
 {
  "horse_name": "ムイ",
  "race_date": "2026-04-26",
  "venue": "福島",
  "race_name": "モルガナイ",
  "surface": "芝",
  "distance": 1200,
  "finish_position": 10,
  "field_size": 16,
  "time_text": "1:08.1",
  "last3f": 33.1,
  "corner_positions": "15-15",
  "track_condition": "良"
 },
 {
  "horse_name": "ムイ",
  "race_date": "2026-01-11",
  "venue": "京都",
  "race_name": "淀短距離S",
  "surface": "芝",
  "distance": 1200,
  "finish_position": 9,
  "field_size": 16,
  "time_text": "1:09.3",
  "last3f": 33.5,
  "corner_positions": "13-13",
  "track_condition": "良"
 },
 {
  "horse_name": "ラヴァンダ",
  "race_date": "2026-08-16",
  "venue": "中京",
  "race_name": "中京記念",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 1,
  "field_size": 16,
  "time_text": "1:31.1",
  "last3f": 33.6,
  "corner_positions": "4-6-6",
  "track_condition": "良"
 },
 {
  "horse_name": "ラヴァンダ",
  "race_date": "2026-05-17",
  "venue": "東京",
  "race_name": "ヴィクトリ",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 7,
  "field_size": 18,
  "time_text": "1:31.6",
  "last3f": 33.6,
  "corner_positions": "8-7",
  "track_condition": "良"
 },
 {
  "horse_name": "ラヴァンダ",
  "race_date": "2026-04-11",
  "venue": "阪神",
  "race_name": "阪神牝馬S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 8,
  "field_size": 10,
  "time_text": "1:32.3",
  "last3f": 33.7,
  "corner_positions": "4-5",
  "track_condition": "良"
 },
 {
  "horse_name": "ラヴァンダ",
  "race_date": "2026-02-10",
  "venue": "東京",
  "race_name": "東京新聞杯",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 2,
  "field_size": 16,
  "time_text": "1:32.3",
  "last3f": 33.3,
  "corner_positions": "9-9",
  "track_condition": "良"
 },
 {
  "horse_name": "ルージュソリテール",
  "race_date": "2026-08-02",
  "venue": "札幌",
  "race_name": "クイーンS",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 6,
  "field_size": 14,
  "time_text": "1:46.7",
  "last3f": 35.3,
  "corner_positions": "3-4-4-3",
  "track_condition": "良"
 },
 {
  "horse_name": "ルージュソリテール",
  "race_date": "2026-06-21",
  "venue": "東京",
  "race_name": "府中牝馬S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 12,
  "field_size": 16,
  "time_text": "1:47.2",
  "last3f": 36.1,
  "corner_positions": "7-2-2",
  "track_condition": "稍"
 },
 {
  "horse_name": "ルージュソリテール",
  "race_date": "2026-04-11",
  "venue": "阪神",
  "race_name": "阪神牝馬S",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 3,
  "field_size": 10,
  "time_text": "1:31.8",
  "last3f": 33.6,
  "corner_positions": "2-2",
  "track_condition": "良"
 },
 {
  "horse_name": "ルージュソリテール",
  "race_date": "2026-03-28",
  "venue": "中京",
  "race_name": "マレーシア",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 1,
  "field_size": 16,
  "time_text": "1:32.2",
  "last3f": 34,
  "corner_positions": "4-4-4",
  "track_condition": "良"
 },
 {
  "horse_name": "ルージュソリテール",
  "race_date": "2026-02-10",
  "venue": "東京",
  "race_name": "初音S",
  "surface": "芝",
  "distance": 1800,
  "finish_position": 2,
  "field_size": 11,
  "time_text": "1:45.8",
  "last3f": 33.2,
  "corner_positions": "2-2-2",
  "track_condition": "良"
 },
 {
  "horse_name": "ワタシマツワ",
  "race_date": "2026-08-30",
  "venue": "札幌",
  "race_name": "日高S",
  "surface": "芝",
  "distance": 1500,
  "finish_position": 1,
  "field_size": 14,
  "time_text": "1:28.1",
  "last3f": 35.3,
  "corner_positions": "1-1-1",
  "track_condition": "良"
 },
 {
  "horse_name": "ワタシマツワ",
  "race_date": "2026-07-26",
  "venue": "札幌",
  "race_name": "羊ヶ丘特別",
  "surface": "芝",
  "distance": 1500,
  "finish_position": 1,
  "field_size": 9,
  "time_text": "1:27.9",
  "last3f": 34.1,
  "corner_positions": "2-2-1",
  "track_condition": "良"
 },
 {
  "horse_name": "ワタシマツワ",
  "race_date": "2026-01-10",
  "venue": "中山",
  "race_name": "初凪賞",
  "surface": "芝",
  "distance": 1600,
  "finish_position": 14,
  "field_size": 16,
  "time_text": "1:35.3",
  "last3f": 35.7,
  "corner_positions": "2-5-6",
  "track_condition": "良"
 },
 {
  "horse_name": "ワタシマツワ",
  "race_date": "2025-12-21",
  "venue": "中京",
  "race_name": "尾張特別",
  "surface": "芝",
  "distance": 1400,
  "finish_position": 14,
  "field_size": 18,
  "time_text": "1:22.8",
  "last3f": 35.8,
  "corner_positions": "4-4",
  "track_condition": "稍"
 },
 {
  "horse_name": "ワタシマツワ",
  "race_date": "2025-10-25",
  "venue": "新潟",
  "race_name": "3歳以上1勝クラス",
  "surface": "芝",
  "distance": 1400,
  "finish_position": 1,
  "field_size": 17,
  "time_text": "1:21.3",
  "last3f": 34.9,
  "corner_positions": "4-4",
  "track_condition": "良"
 }
];

