export function historyCollectionPage(today){return `<!doctype html><html lang="ja"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KEIBA LABO｜過去走の収集</title><style>body{margin:0;background:#f3f6f5;color:#20372d;font:16px system-ui,sans-serif}main{max-width:1040px;margin:auto;padding:28px 18px}h1{font-size:28px}p{line-height:1.7}.panel{background:white;border:1px solid #dce5df;border-radius:16px;padding:20px;margin:18px 0}form{display:flex;gap:14px;flex-wrap:wrap;align-items:end}label{display:grid;gap:7px}select,input,button{font:inherit;padding:10px;border:1px solid #b4c6ba;border-radius:8px}button{background:#176643;color:white;cursor:pointer}button:disabled{opacity:.45;cursor:wait}.stats{display:flex;gap:22px;flex-wrap:wrap}.stats strong{font-size:26px;display:block}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}td,th{text-align:left;padding:12px;border-bottom:1px solid #e6ece8}.muted{color:#5b6b62;font-size:14px}a{color:#176643}#message{white-space:pre-wrap}</style><main><p class="muted">KEIBA LABO / データの補充</p><h1>過去走の収集状況</h1><p>保存済みの正式出馬表に載る馬から、足りない過去走を少しずつ取得します。対象日以降の結果は収集に含めません。</p><section class="panel"><form id="form"><label>開催日<input name="date" type="date" value="${today}" required></label><label>競馬場<select name="venue">${['東京','中山','京都','阪神','札幌','函館','福島','新潟','中京','小倉'].map(x=>'<option>'+x+'</option>').join('')}</select></label><label>レース<select name="raceNo">${Array.from({length:12},(_,i)=>'<option value="'+(i+1)+'"'+(i===10?' selected':'')+'>'+(i+1)+'R</option>').join('')}</select></label><label>各馬の保存目安<select name="historyLimit"><option value="10">直近10走</option><option value="20">直近20走</option></select></label><button>保存状況を見る</button></form></section><section class="panel"><p id="message" role="status" aria-live="polite">日付とレースを選んでください。</p><div id="stats" class="stats"></div><p><button id="collect" disabled>未確認の馬を1頭収集</button> <a id="assess" hidden>このレースを精査する</a></p><p class="muted">取得は同時に1処理、外部アクセスの間隔は5秒以上、処理の間隔は1分以上。定期収集は毎時30分に最大1頭を進めます。混雑応答があれば1時間休止します。</p><div class="scroll"><table><thead><tr><th>馬番・馬名</th><th>保存済み過去走</th><th>上がりあり</th><th>最古の記録</th><th>収集状態</th></tr></thead><tbody id="rows"></tbody></table></div></section><p class="muted">「上がりあり」は保存済みの数です。JRA馬プロフィールに上がり欄がない過去走は空欄のまま保持し、保存済みの上がりを消しません。10年分の全レース収集はまだ完了していません。精査で利用する走数はモデル側の上限に従います。</p><p><a href="/lab/history-assessment">全レースの精査へ</a></p></main><script>
const f=document.querySelector('#form'),message=document.querySelector('#message'),button=document.querySelector('#collect');let current=null,busy=false;
const esc=v=>String(v??'―').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const input=()=>Object.fromEntries(new FormData(f));
function render(data){current=data;document.querySelector('#stats').innerHTML=[['出走馬',data.runnerCount+'頭'],['保存済み過去走',data.totalStoredRows+'件'],['上がりあり',data.last3fRows+'件'],['未確認・再確認待ち',data.remainingHorses+'頭']].map(([label,n])=>'<div><strong>'+esc(n)+'</strong>'+esc(label)+'</div>').join('');document.querySelector('#rows').innerHTML=data.runners.map(r=>'<tr><td>'+esc(r.horseNo)+' '+esc(r.horseName)+'</td><td>'+esc(r.storedRows)+'走</td><td>'+esc(r.last3fRows)+'走</td><td>'+esc(r.oldestDate)+'</td><td>'+esc(r.collectionState==='failed'?'取得待ち（前回未取得）':r.due?'未確認・再確認待ち':r.collectionState==='stored-enough'?'保存目安に到達':'確認済み')+'</td></tr>').join('');button.disabled=busy||data.pendingHorses===0;const link=document.querySelector('#assess');link.hidden=false;link.href='/lab/history-assessment?'+new URLSearchParams({date:data.race.date,venue:data.race.venue,race_no:data.race.raceNo});}
async function status(){const x=input();const response=await fetch('/v1/lab/history-collection-status?'+new URLSearchParams({...x,race_no:x.raceNo,history_limit:x.historyLimit}));const data=await response.json();if(!response.ok||!data.ok)throw Error(data.error||'取得できませんでした');render(data);return data;}
f.addEventListener('submit',async e=>{e.preventDefault();busy=true;button.disabled=true;message.textContent='保存状況を確認しています…';try{const data=await status();message.textContent=data.race.raceName+'：保存済みDBを確認しました。'}catch(e){current=null;message.textContent=e.message;document.querySelector('#stats').replaceChildren();document.querySelector('#rows').replaceChildren();document.querySelector('#assess').hidden=true}finally{busy=false;button.disabled=!current||current.pendingHorses===0}});
f.addEventListener('change',()=>{current=null;button.disabled=true;document.querySelector('#assess').hidden=true;message.textContent='条件を変更しました。「保存状況を見る」で確認してください。'});
button.addEventListener('click',async()=>{if(busy||!current)return;busy=true;button.disabled=true;message.textContent='JRAから1頭分を取得しています…';try{const r=await fetch('/v1/lab/history-collection-batch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...input(),batchSize:1,confirm:'COLLECT'})});const data=await r.json();if(data.after)render(data.after);if(data.status==='cooldown')message.textContent='取得間隔を空けています。しばらくしてから再確認してください。';else if(data.status==='complete')message.textContent='今回は再取得が必要な馬はいません。';else if(data.results)message.textContent='今回の新規保存：'+(data.addedRows||0)+'件。'+data.results.map(x=>x.horseName+'：'+(x.status==='failed'?x.error:x.savedRows+'走を確認')).join(' / ');else throw Error(data.error||'取得できませんでした');}catch(e){message.textContent=e.message}finally{busy=false;button.disabled=!current||current.pendingHorses===0}});
const q=new URLSearchParams(location.search);for(const k of ['date','venue','raceNo','historyLimit'])if(q.has(k))f.elements.namedItem(k).value=q.get(k);if(q.has('date'))f.requestSubmit();
</script></html>`}
