import app from "./index-v3.6.0.js";

function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=UTF-8","access-control-allow-origin":"*"}})}
function validDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||"")}
function jstDate(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const o=Object.fromEntries(p.filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`}
function addDays(date,days){const d=new Date(`${date}T00:00:00+09:00`);d.setUTCDate(d.getUTCDate()+days);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function programUrl(date){const[y,m,d]=date.split("-");return `https://www.jra.go.jp/keiba/calendar${y}/${y}/${Number(m)}/${m}${d}.html`}

const VENUES="札幌|函館|福島|新潟|東京|中山|中京|京都|阪神|小倉";
function decodeEntities(s){return String(s||"").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#44;/gi,",").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)))}
function structuredText(html){return decodeEntities(String(html||"")
  .replace(/<script[\s\S]*?<\/script>/gi," ")
  .replace(/<style[\s\S]*?<\/style>/gi," ")
  .replace(/<br\s*\/?\s*>/gi,"\n")
  .replace(/<\/(?:tr|table|thead|tbody|tfoot|h[1-6]|section|article|li|p)>/gi,"\n")
  .replace(/<\/(?:div|dl|dt|dd)>/gi,"\n")
  .replace(/<[^>]+>/g," "))
  .split(/\r?\n/)
  .map(x=>x.replace(/[\u3000\t ]+/g," ").trim())
  .filter(Boolean)
  .join("\n");}
function flatText(s){return String(s||"").replace(/\n+/g," ").replace(/\s+/g," ").replace(/([0-9]),([0-9]{3})/g,"$1$2").trim()}
function parseLabel(label){const t=String(label||"").replace(/([0-9]),([0-9]{3})/g,"$1$2").replace(/\s+/g," ").trim();const c=t.match(/([123]\d{3})\s*[（(]\s*(芝(?:・外)?|ダ|障害)\s*[）)]/);const raw=c?.[2]||null;const surface=raw?.startsWith("芝")?"芝":raw==="ダ"?"ダート":raw||null;const distance=c?Number(c[1]):null;const grade=(t.match(/[（(]\s*(GⅠ|GⅡ|GⅢ|L)\s*[）)]/)||[])[1]||null;return{label:t,surface,distance,grade}}
function rowToRace(line,current,date,sourceUrl){const s=String(line||"").replace(/([0-9]),([0-9]{3})/g,"$1$2").replace(/\s+/g," ").trim();const m=s.match(/(?:^|\s)([1-9]|1[0-2])\s*レース\s+(.+?)\s+(\d{1,2})\s*時\s*(\d{2})\s*分(?:\s|$)/);if(!m||!current)return null;const raceNo=Number(m[1]),p=parseLabel(m[2]);return{programKey:`${date}:${current.venue}:${raceNo}`,date,venue:current.venue,meetingNo:current.meetingNo,dayNo:current.dayNo,raceNo,raceLabel:p.label,surface:p.surface,distance:p.distance,startTime:`${m[3].padStart(2,"0")}:${m[4]}`,grade:p.grade,sourceUrl}}
function parseStructured(html,date,sourceUrl){const txt=structuredText(html);const lines=txt.split("\n");const races=[];const seen=new Set();const headers=[];let current=null;const vre=new RegExp(`(\\d+)\\s*回\\s*(${VENUES})\\s*(\\d+)\\s*日`);for(const line of lines){const vm=line.match(vre);if(vm){current={meetingNo:Number(vm[1]),venue:vm[2],dayNo:Number(vm[3])};headers.push({...current,line});continue}const r=rowToRace(line,current,date,sourceUrl);if(r&&!seen.has(r.programKey)){seen.add(r.programKey);races.push(r)}}return{races,headers,textSample:lines.slice(Math.max(0,lines.findIndex(x=>x.includes("競馬番組"))),Math.max(0,lines.findIndex(x=>x.includes("競馬番組")))+35)}}
function parseFlat(html,date,sourceUrl){const text=flatText(structuredText(html));const vre=new RegExp(`(\\d+)\\s*回\\s*(${VENUES})\\s*(\\d+)\\s*日`,`g`);const headers=[];let m;while((m=vre.exec(text)))headers.push({index:m.index,meetingNo:Number(m[1]),venue:m[2],dayNo:Number(m[3])});const races=[],seen=new Set();for(let i=0;i<headers.length;i++){const h=headers[i],end=i+1<headers.length?headers[i+1].index:text.length,section=text.slice(h.index,end);const rr=/([1-9]|1[0-2])\s*レース\s+([\s\S]*?)\s+(\d{1,2})\s*時\s*(\d{2})\s*分/g;let r;while((r=rr.exec(section))){const raceNo=Number(r[1]);const p=parseLabel(r[2]);const key=`${date}:${h.venue}:${raceNo}`;if(seen.has(key)||!p.label||p.label.length>240)continue;seen.add(key);races.push({programKey:key,date,venue:h.venue,meetingNo:h.meetingNo,dayNo:h.dayNo,raceNo,raceLabel:p.label,surface:p.surface,distance:p.distance,startTime:`${r[3].padStart(2,"0")}:${r[4]}`,grade:p.grade,sourceUrl})}}return{races,headers,textSample:text.slice(Math.max(0,text.indexOf("競馬番組")),Math.max(0,text.indexOf("競馬番組"))+1000)}}
function parseBest(body,date,sourceUrl){const a=parseStructured(body,date,sourceUrl),b=parseFlat(body,date,sourceUrl);return b.races.length>a.races.length?{...b,parser:"flat-section"}:{...a,parser:"structured-lines"}}
async function fetchDecoded(url,date){const r=await fetch(url,{headers:{"user-agent":"keiba-lab/3.6.1 (+JRA all-race parser repair)",accept:"text/html,*/*;q=0.8"},redirect:"follow"});const buf=await r.arrayBuffer();const candidates=[];for(const enc of["utf-8","shift_jis"]){try{const body=new TextDecoder(enc).decode(buf);const parsed=parseBest(body,date,r.url);const bad=(body.match(/�/g)||[]).length;candidates.push({encoding:enc,body,parsed,score:parsed.races.length*100+parsed.headers.length*10-bad})}catch{}}candidates.sort((x,y)=>y.score-x.score);const best=candidates[0]||{encoding:"unknown",body:"",parsed:{races:[],headers:[],textSample:"",parser:"none"},score:-999};return{ok:r.ok,status:r.status,url:r.url,bytes:buf.byteLength,...best,alternates:candidates.map(x=>({encoding:x.encoding,races:x.parsed.races.length,headers:x.parsed.headers.length,score:x.score}))}}
async function ensureProgramTable(db){await db.prepare(`CREATE TABLE IF NOT EXISTS jra_race_program (program_key TEXT PRIMARY KEY,race_date TEXT NOT NULL,venue TEXT NOT NULL,meeting_no INTEGER,day_no INTEGER,race_no INTEGER NOT NULL,race_label TEXT,surface TEXT,distance INTEGER,start_time TEXT,grade TEXT,source_url TEXT NOT NULL,fetched_at TEXT NOT NULL)`).run()}
async function persistPrograms(db,races){const now=new Date().toISOString();for(const r of races)await db.prepare(`INSERT INTO jra_race_program (program_key,race_date,venue,meeting_no,day_no,race_no,race_label,surface,distance,start_time,grade,source_url,fetched_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(program_key) DO UPDATE SET meeting_no=excluded.meeting_no,day_no=excluded.day_no,race_label=excluded.race_label,surface=excluded.surface,distance=excluded.distance,start_time=excluded.start_time,grade=excluded.grade,source_url=excluded.source_url,fetched_at=excluded.fetched_at`).bind(r.programKey,r.date,r.venue,r.meetingNo,r.dayNo,r.raceNo,r.raceLabel,r.surface,r.distance,r.startTime,r.grade,r.sourceUrl,now).run();return now}
async function stageProgram(env,date,debug=false){if(!validDate(date))throw new Error("date must be YYYY-MM-DD");await ensureProgramTable(env.DB);const page=await fetchDecoded(programUrl(date),date);if(!page.ok)return{ok:false,stage:"all-race-program-staging",version:"3.6.1",date,httpStatus:page.status,error:"JRA program page not available"};const races=page.parsed.races;if(!races.length)return{ok:false,stage:"all-race-program-staging",version:"3.6.1",date,httpStatus:page.status,encoding:page.encoding,parser:page.parsed.parser,alternates:page.alternates,venueHeadersFound:page.parsed.headers.length,error:"No race rows parsed",debug:debug?{headers:page.parsed.headers,textSample:page.parsed.textSample}:undefined};const fetchedAt=await persistPrograms(env.DB,races);const byVenue={};for(const x of races)byVenue[x.venue]=(byVenue[x.venue]||0)+1;return{ok:true,stage:"all-race-program-staging",version:"3.6.1",date,httpStatus:page.status,encoding:page.encoding,parser:page.parsed.parser,raceCount:races.length,gradedCount:races.filter(x=>x.grade).length,nonGradedCount:races.filter(x=>!x.grade).length,venueSummary:Object.entries(byVenue).map(([venue,raceCount])=>({venue,raceCount})),races,fetchedAt}}
async function prepDates(request,env){const u=new URL(request.url),raw=u.searchParams.get("dates"),dates=(raw?raw.split(","):Array.from({length:8},(_,i)=>addDays(jstDate(),i))).map(x=>x.trim()).filter(validDate);const runs=[];for(const date of dates){const d=await stageProgram(env,date);runs.push({date,httpStatus:d.httpStatus||200,ok:Boolean(d.ok),encoding:d.encoding||null,parser:d.parser||null,raceCount:Number(d.raceCount||0),gradedCount:Number(d.gradedCount||0),nonGradedCount:Number(d.nonGradedCount||0),venues:d.venueSummary||[],alternates:d.alternates||undefined,error:d.error||null})}const successful=runs.filter(x=>x.ok),total=successful.reduce((s,x)=>s+x.raceCount,0),graded=successful.reduce((s,x)=>s+x.gradedCount,0),non=successful.reduce((s,x)=>s+x.nonGradedCount,0);return{ok:successful.length>0,stage:"multi-day-all-race-program-prep",version:"3.6.1",requestedDates:dates,successfulDates:successful.length,totalProgramRaces:total,gradedRaces:graded,nonGradedRaces:non,nonGradedSharePct:total?Math.round(non/total*1000)/10:0,runs,policy:{rawProgramStorage:"ALL official JRA races",gradedOnly:false,featurePriority:"graded and selected races get expensive analysis first"}}}

export default{async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==="/")return json({ok:true,service:"keiba-lab-api",version:"3.6.1",phase:"JRA program parser repaired"});if(!env.DB)return json({ok:false,error:"D1 binding DB is not configured"},500);try{if(u.pathname==="/v1/lab/program-stage")return json(await stageProgram(env,u.searchParams.get("date")||"2026-10-10",u.searchParams.get("debug")==="1"));if(u.pathname==="/v1/lab/program-debug")return json(await stageProgram(env,u.searchParams.get("date")||"2026-10-10",true));if(u.pathname==="/v1/lab/meeting-prep")return json(await prepDates(request,env));if(u.pathname==="/v1/lab/deploy-check")return json({ok:true,version:"3.6.1",build:"structured-JRA-program-parser",todayJst:jstDate(),now:new Date().toISOString()});return app.fetch(request,env,ctx)}catch(error){return json({ok:false,version:"3.6.1",error:String(error)},500)}},async scheduled(event,env,ctx){ctx.waitUntil((async()=>{for(let i=0;i<8;i++){const date=addDays(jstDate(),i);try{await stageProgram(env,date)}catch(error){console.error("program stage failed",date,String(error))}}})())}};
