import app from './index-v3.24.0.js';import {assignReplayMarks,validateReplay,REPLAY_EVIDENCE} from './replay-v3.25.0.js';
export const VERSION='3.25.0';const H={'content-type':'application/json; charset=UTF-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'};const json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:H});const valid=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'');
const OFFICIAL_STARTS={'2026-10-04|東京|11':{startAt:'2026-10-04T15:45:00+09:00',source:'JRA official racecard',sourceUrl:'https://jra.jp/JRADB/accessD.html?CNAME=pw01dde1005202604021120261004%2FA4'}};
async function one(db,q,a=[]){try{return await db.prepare(q).bind(...a).first()}catch{return null}}
async function ensure(db){await db.prepare(`CREATE TABLE IF NOT EXISTS lab_race_start_evidence(race_key TEXT PRIMARY KEY,start_at TEXT NOT NULL,source TEXT NOT NULL,source_url TEXT NOT NULL,observed_at TEXT NOT NULL)`).run()}
async function resolveRace(db,{date,venue,raceNo}){return one(db,'SELECT race_key,race_date,venue,race_no,race_name,runner_count FROM jra_races WHERE race_date=? AND venue=? AND race_no=?',[date,venue,raceNo])}
async function startEvidence(db,r){await ensure(db);const x=await one(db,'SELECT start_at,source,source_url,observed_at FROM lab_race_start_evidence WHERE race_key=?',[r.race_key]);if(x)return{startAt:x.start_at,source:x.source,sourceUrl:x.source_url,observedAt:x.observed_at,stored:true};const k=`${r.race_date}|${r.venue}|${r.race_no}`;return OFFICIAL_STARTS[k]?{...OFFICIAL_STARTS[k],observedAt:null,stored:false}:null}
async function invoke(request,env,ctx,path,params={}){const u=new URL(request.url);u.pathname=path;u.search='';for(const[k,v]of Object.entries(params))if(v!=null)u.searchParams.set(k,String(v));const r=await app.fetch(new Request(u.href,{method:'GET'}),env,ctx);let d=null;try{d=await r.json()}catch{}return{status:r.status,data:d}}
async function legacyRows(db,r,startAt){try{const q=await db.prepare(`SELECT horse_no,horse_name,model_version,track_condition,evidence_score,model_coverage_pct,confidence_pct,generated_at FROM lab_prediction_snapshots WHERE race_key=? AND generated_at<? ORDER BY generated_at DESC,evidence_score DESC`).bind(r.race_key,startAt).all();const rows=q.results||[];if(!rows.length)return null;const newest=rows[0].generated_at,group=rows.filter(x=>x.generated_at===newest);if(group.length!==Number(r.runner_count||0))return null;return{generatedAt:newest,modelVersion:group[0].model_version,trackCondition:group[0].track_condition,runners:assignReplayMarks(group.map(x=>({horseNo:Number(x.horse_no),horseName:x.horse_name,evidenceScore:x.evidence_score==null?null:Number(x.evidence_score),modelCoveragePct:x.model_coverage_pct==null?null:Number(x.model_coverage_pct),confidencePct:x.confidence_pct==null?null:Number(x.confidence_pct)})))} }catch{return null}}
async function evidence(request,env,ctx,id){const r=await resolveRace(env.DB,id);if(!r)return{status:404,data:{ok:false,error:'race not found'}};const start=await startEvidence(env.DB,r);const p=await invoke(request,env,ctx,'/v1/lab/labo-prediction',id);if(p.data?.prediction?.available===true&&p.data.prediction.hashVerified===true)return{status:200,data:{ok:true,version:VERSION,race:r,evidence:{grade:REPLAY_EVIDENCE.VERIFIED,label:'🔒 VERIFIED',eligibleForAccuracy:true,reason:'immutable pre-result seal with verified SHA-256'},prediction:p.data.prediction,startEvidence:start}};
 if(start){const legacy=await legacyRows(env.DB,r,start.startAt);if(legacy)return{status:200,data:{ok:true,version:VERSION,race:r,evidence:{grade:REPLAY_EVIDENCE.LEGACY,label:'📦 LEGACY SAVED',eligibleForAccuracy:true,reason:'complete LABO score snapshot stored before verified start time'},prediction:legacy,startEvidence:start}}}
 if(!start)return{status:200,data:{ok:true,version:VERSION,race:r,evidence:{grade:REPLAY_EVIDENCE.NONE,label:'— NO RECORD',eligibleForAccuracy:false,reason:'race-start evidence missing; replay refused'},prediction:null,startEvidence:null}};
 const rank=await invoke(request,env,ctx,'/v1/lab/rank',{date:r.race_date,venue:r.venue,race_no:r.race_no,track:id.track||null});const check=validateReplay({raceDate:r.race_date,startAt:start.startAt,sourceUrl:start.sourceUrl,ranking:rank.data});if(!check.eligible)return{status:200,data:{ok:true,version:VERSION,race:r,evidence:{grade:REPLAY_EVIDENCE.NONE,label:'— NO RECORD',eligibleForAccuracy:false,reason:check.reason},prediction:null,startEvidence:start}};
 const marked=assignReplayMarks(rank.data.runners||[]);return{status:200,data:{ok:true,version:VERSION,race:r,evidence:{grade:REPLAY_EVIDENCE.REPLAY,label:'🔁 RESULT-BLIND REPLAY',eligibleForAccuracy:false,reason:check.reason},prediction:{available:true,locked:false,diagnostic:true,modelVersion:rank.data.version||'legacy-rank',trackCondition:rank.data.race?.trackConditionInput||null,runners:marked,top5:marked.slice(0,5)},startEvidence:start,guardrails:{officialResultsQueried:false,targetRaceHistoryExcluded:true,notCountedAsProspectiveAccuracy:true,postRaceReconstructionLabelled:true}}}}
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(u.pathname==='/')return json({ok:true,service:'keiba-lab-api',version:VERSION,phase:'prediction evidence + result-blind replay'});if(u.pathname==='/v1/lab/deploy-check')return json({ok:true,version:VERSION,build:'result-blind-replay',now:new Date().toISOString()});if(!env.DB)return json({ok:false,version:VERSION,error:'D1 DB missing'},500);try{if(u.pathname==='/v1/lab/prediction-evidence'&&request.method==='GET'){const id={date:u.searchParams.get('date'),venue:u.searchParams.get('venue'),raceNo:Number(u.searchParams.get('race_no')||u.searchParams.get('raceNo')),track:u.searchParams.get('track')||null};if(!valid(id.date)||!id.venue||!Number.isInteger(id.raceNo)||id.raceNo<1||id.raceNo>12)return json({ok:false,version:VERSION,error:'date, venue, race_no=1-12 required'},400);const x=await evidence(request,env,ctx,id);return json(x.data,x.status)}const r=await app.fetch(request,env,ctx);let d;try{d=await r.clone().json()}catch{return r}if(d&&typeof d==='object')d.version=VERSION;return json(d,r.status)}catch(e){return json({ok:false,version:VERSION,error:String(e?.message||e)},500)}},async scheduled(event,env,ctx){return app.scheduled(event,env,ctx)}};
