import app from './index-v3.18.0.js';import {summarizePerformance} from './performance-v3.19.0.js';
export const VERSION='3.19.0';const H={'content-type':'application/json; charset=UTF-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'};const json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:H});const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'');
async function rows(db,q,a=[]){return((await db.prepare(q).bind(...a).all()).results||[])}
async function performance(db,u){const from=u.searchParams.get('from')||'2000-01-01',to=u.searchParams.get('to')||'2999-12-31';if(!validDate(from)||!validDate(to)||from>to)throw new Error('from/to must be YYYY-MM-DD and from <= to');
 const locks=(await rows(db,`SELECT race_key,snapshot_json snapshot,sealed_at FROM lab_model_locks WHERE model_version='3.3.0-prospective' AND SUBSTR(race_key,1,10) BETWEEN ? AND ? ORDER BY sealed_at DESC`,[from,to])).map(x=>({raceKey:x.race_key,snapshot:x.snapshot,sealedAt:x.sealed_at}));
 const outcomes=(await rows(db,`SELECT race_key,horse_no,finish_position FROM lab_race_result_details WHERE SUBSTR(race_key,1,10) BETWEEN ? AND ?`,[from,to])).map(x=>({raceKey:x.race_key,horseNo:Number(x.horse_no),finishPosition:x.finish_position==null?null:Number(x.finish_position)}));
 let user=[];try{user=(await rows(db,`SELECT race_key,audit_json audit,created_at FROM lab_user_mark_revisions WHERE SUBSTR(race_key,1,10) BETWEEN ? AND ? ORDER BY created_at DESC`,[from,to])).map(x=>({raceKey:x.race_key,audit:x.audit,createdAt:x.created_at}))}catch{}
 return{from,to,...summarizePerformance({locks,outcomes,userRevisions:user})}}
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(u.pathname==='/')return json({ok:true,service:'keiba-lab-api',version:VERSION,phase:'locked prediction performance dashboard'});if(u.pathname==='/v1/lab/deploy-check')return json({ok:true,version:VERSION,build:'prospective-performance-dashboard',now:new Date().toISOString()});if(!env.DB)return json({ok:false,version:VERSION,error:'D1 DB missing'},500);try{if(u.pathname==='/v1/lab/performance'&&request.method==='GET')return json({ok:true,version:VERSION,performance:await performance(env.DB,u)});const r=await app.fetch(request,env,ctx);let d;try{d=await r.clone().json()}catch{return r}if(d&&typeof d==='object')d.version=VERSION;return json(d,r.status)}catch(e){return json({ok:false,version:VERSION,error:String(e?.message||e)},400)}},async scheduled(event,env,ctx){return app.scheduled(event,env,ctx)}};
