import app from "./index-v3.5.0.js";

function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=UTF-8","access-control-allow-origin":"*"}})}
function validDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||"")}
function jstDate(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const o=Object.fromEntries(p.filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`}
function addDays(date,days){const d=new Date(`${date}T00:00:00+09:00`);d.setUTCDate(d.getUTCDate()+days);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function programUrl(date){const[y,m,d]=date.split("-");return `https://www.jra.go.jp/keiba/calendar${y}/${y}/${Number(m)}/${m}${d}.html`}
function cleanHtml(html){return String(html||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<br\s*\/?\s*>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&#44;/g,",").replace(/\s+/g," ").trim()}
function decodeScore(s){let n=0;for(const k of["競馬番組","レース番号","発走時刻","東京","京都","レース"])if(s.includes(k))n+=10;if(/\d+回(?:東京|京都|阪神|中山|中京|新潟|福島|札幌|函館|小倉)\d+日/.test(s))n+=20;n-=((s.match(/�/g)||[]).length*2);return n}
async function fetchJra(url){const r=await fetch(url,{headers:{"user-agent":"keiba-lab/3.6.0 (+robust official JRA program parser)",accept:"text/html,*/*;q=0.8"},redirect:"follow"});const b=await r.arrayBuffer();const dec=[];for(const enc of["utf-8","shift_jis"]){try{const body=new TextDecoder(enc).decode(b);dec.push({enc,body,score:decodeScore(body)})}catch{}}dec.sort((a,b)=>b.score-a.score);const best=dec[0]||{enc:"unknown",body:"",score:-999};return{ok:r.ok,status:r.status,url:r.url,body:best.body,encoding:best.enc,decodeScore:best.score,bytes:b.byteLength}}
async function ensureProgramTable(db){await db.prepare(`CREATE TABLE IF NOT EXISTS jra_race_program (program_key TEXT PRIMARY KEY,race_date TEXT NOT NULL,venue TEXT NOT NULL,meeting_no INTEGER,day_no INTEGER,race_no INTEGER NOT NULL,race_label TEXT,surface TEXT,distance INTEGER,start_time TEXT,grade TEXT,source_url TEXT NOT NULL,fetched_at TEXT NOT NULL)`).run()}
function parsePrograms(html,date,sourceUrl){
  const text=cleanHtml(html).replace(/([0-9]),([0-9]{3})/g,"$1$2");
  const venueRe=/(\d+)回(札幌|函館|福島|新潟|東京|中山|中京|京都|阪神|小倉)(\d+)日/g;
  const headers=[];let m;while((m=venueRe.exec(text)))headers.push({index:m.index,meetingNo:Number(m[1]),venue:m[2],dayNo:Number(m[3])});
  const races=[];
  for(let i=0;i<headers.length;i++){
    const h=headers[i],end=i+1<headers.length?headers[i+1].index:text.length,section=text.slice(h.index,end);
    const raceRe=/(?:^|\s)([1-9]|1[0-2])レース\s+([\s\S]*?)\s+(\d{1,2})時(\d{2})分(?=\s|$)/g;let r;
    while((r=raceRe.exec(section))){
      const raceNo=Number(r[1]);let label=r[2].replace(/\s+/g," ").trim();
      if(!label||label.length>220)continue;
      const course=label.match(/([123]\d{3})\s*[（(](芝(?:・外)?|ダ|障害)[）)]/);
      const distance=course?Number(course[1]):null,raw=course?course[2]:null;
      const surface=raw?.startsWith("芝")?"芝":raw==="ダ"?"ダート":raw||null;
      const grade=(label.match(/[（(](GⅠ|GⅡ|GⅢ|L)[）)]/)||[])[1]||null;
      races.push({programKey:`${date}:${h.venue}:${raceNo}`,date,venue:h.venue,meetingNo:h.meetingNo,dayNo:h.dayNo,raceNo,raceLabel:label,surface,distance,startTime:`${r[3].padStart(2,"0")}:${r[4]}`,grade,sourceUrl});
    }
  }
  return{headers,races,textSample:text.slice(Math.max(0,text.indexOf("競馬番組")),Math.max(0,text.indexOf("競馬番組"))+700)};
}
async function persistPrograms(db,races){const now=new Date().toISOString();for(const r of races)await db.prepare(`INSERT INTO jra_race_program (program_key,race_date,venue,meeting_no,day_no,race_no,race_label,surface,distance,start_time,grade,source_url,fetched_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(program_key) DO UPDATE SET meeting_no=excluded.meeting_no,day_no=excluded.day_no,race_label=excluded.race_label,surface=excluded.surface,distance=excluded.distance,start_time=excluded.start_time,grade=excluded.grade,source_url=excluded.source_url,fetched_at=excluded.fetched_at`).bind(r.programKey,r.date,r.venue,r.meetingNo,r.dayNo,r.raceNo,r.raceLabel,r.surface,r.distance,r.startTime,r.grade,r.sourceUrl,now).run();return now}
async function stageProgram(env,date,debug=false){if(!validDate(date))throw new Error("date must be YYYY-MM-DD");await ensureProgramTable(env.DB);const url=programUrl(date),page=await fetchJra(url);if(!page.ok)return{ok:false,stage:"all-race-program-staging",version:"3.6.0",date,httpStatus:page.status,sourceUrl:url,error:"JRA program page not available"};const parsed=parsePrograms(page.body,date,page.url),races=parsed.races;if(!races.length)return{ok:false,stage:"all-race-program-staging",version:"3.6.0",date,httpStatus:page.status,sourceUrl:page.url,encoding:page.encoding,decodeScore:page.decodeScore,venueHeadersFound:parsed.headers.length,error:"No race rows parsed",debug:debug?{headers:parsed.headers,textSample:parsed.textSample}:undefined};const fetchedAt=await persistPrograms(env.DB,races);const byVenue={};for(const r of races)byVenue[r.venue]=(byVenue[r.venue]||0)+1;return{ok:true,stage:"all-race-program-staging",version:"3.6.0",date,httpStatus:page.status,encoding:page.encoding,decodeScore:page.decodeScore,raceCount:races.length,gradedCount:races.filter(r=>r.grade).length,nonGradedCount:races.filter(r=>!r.grade).length,venueSummary:Object.entries(byVenue).map(([venue,raceCount])=>({venue,raceCount})),races,fetchedAt,storagePolicy:{baseDataset:"ALL official JRA races",gradedOnly:false,heavyFeatureAnalysis:"graded races and selected targets prioritized",prospectiveLocks:"selected validation targets only"}}}
async function prepDates(request,env){const u=new URL(request.url),raw=u.searchParams.get("dates"),dates=(raw?raw.split(","):Array.from({length:8},(_,i)=>addDays(jstDate(),i))).map(x=>x.trim()).filter(validDate);if(!dates.length)throw new Error("dates must contain YYYY-MM-DD values");if(dates.length>14)throw new Error("maximum 14 dates per request");const runs=[];for(const date of dates){const d=await stageProgram(env,date);runs.push({date,httpStatus:d.httpStatus||200,ok:Boolean(d.ok),encoding:d.encoding||null,raceCount:Number(d.raceCount||0),gradedCount:Number(d.gradedCount||0),nonGradedCount:Number(d.nonGradedCount||0),venues:d.venueSummary||[],error:d.error||null})}const successful=runs.filter(x=>x.ok),total=successful.reduce((s,x)=>s+x.raceCount,0),graded=successful.reduce((s,x)=>s+x.gradedCount,0),non=successful.reduce((s,x)=>s+x.nonGradedCount,0);return{ok:successful.length>0,stage:"multi-day-all-race-program-prep",version:"3.6.0",requestedDates:dates,successfulDates:successful.length,totalProgramRaces:total,gradedRaces:graded,nonGradedRaces:non,nonGradedSharePct:total?Math.round(non/total*1000)/10:0,runs,policy:{rawProgramStorage:"ALL official JRA races",gradedOnly:false,featurePriority:"graded and selected races get expensive analysis first",prospectiveValidation:"selected targets only; never limits base-data accumulation"},next:"When official race cards publish, ingest every race card for the meeting day, while sealing holdout predictions only for selected targets."}}
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==="/")return json({ok:true,service:"keiba-lab-api",version:"3.6.0",phase:"robust all-race program parsing"});if(!env.DB)return json({ok:false,error:"D1 binding DB is not configured"},500);try{if(u.pathname==="/v1/lab/program-stage")return json(await stageProgram(env,u.searchParams.get("date")||"2026-10-10",u.searchParams.get("debug")==="1"));if(u.pathname==="/v1/lab/meeting-prep")return json(await prepDates(request,env));if(u.pathname==="/v1/lab/program-debug")return json(await stageProgram(env,u.searchParams.get("date")||"2026-10-10",true));if(u.pathname==="/v1/lab/deploy-check")return json({ok:true,version:"3.6.0",build:"robust-all-race-program-parser",todayJst:jstDate(),now:new Date().toISOString()});return app.fetch(request,env,ctx)}catch(error){return json({ok:false,version:"3.6.0",error:String(error)},500)}},async scheduled(event,env,ctx){ctx.waitUntil((async()=>{const dates=Array.from({length:8},(_,i)=>addDays(jstDate(),i));for(const date of dates){try{await stageProgram(env,date)}catch(error){console.error("program stage failed",date,String(error))}}})())}};
