import app from './index-v3.38.0.js';
import {enqueueArchive,collectArchiveBatch,archiveStatus} from './archive-collection-v3.39.0.js';
import {archivePage} from './archive-page-v3.39.0.js';
import {collectRichResult,richResultStatus,scheduledRichResult} from './rich-result-collection-v3.39.0.js';
import {discoverResultSource} from './official-result-sources-v3.39.0.js';
import {scheduledCollection} from './history-collection-v3.37.0.js';
import {scheduledExperiment} from './learning-experiment-v3.36.0.js';
import {runPipelineJob,pipelineStatus} from './pipeline-runs-v3.39.0.js';
export const VERSION='3.39.0',RESULT_CRON='8,18,28,38,48,58 * * * *';
const H={'content-type':'application/json; charset=UTF-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization','cache-control':'no-store'},json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:H});
async function status(db){const d=await archiveStatus(db);d.execution=await pipelineStatus(db);d.results=[];for(const t of d.targets){const r=await richResultStatus(db,t.date);d.results.push({date:t.date,races:r.races,completeRaces:r.completeRaces,richCompleteRaces:r.richCompleteRaces})}return d}
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(u.pathname==='/')return json({ok:true,service:'keiba-lab-api',version:VERSION,phase:'published historical result links and observed bounded jobs'});if(u.pathname==='/v1/lab/deploy-check')return json({ok:true,version:VERSION,build:'historical-card-result-bridge',now:new Date().toISOString()});if(u.pathname==='/lab/archive-collection'&&request.method==='GET')return new Response(archivePage(),{headers:{'content-type':'text/html; charset=UTF-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
try{
 if(u.pathname==='/v1/lab/archive-status'&&request.method==='GET')return json({...await status(env.DB),version:VERSION});
 if(u.pathname==='/v1/lab/pipeline-status'&&request.method==='GET')return json({ok:true,...await pipelineStatus(env.DB),version:VERSION});
 if(['/v1/lab/result-learning-status','/v1/lab/history-result-status'].includes(u.pathname)&&request.method==='GET')return json({...await richResultStatus(env.DB,u.searchParams.get('date')),version:VERSION});
 if(u.pathname==='/v1/lab/archive-enqueue'&&request.method==='POST'){const b=await request.json();if(b.confirm!=='QUEUE')throw Error('confirm QUEUE is required');return json({...await enqueueArchive(env.DB,b.dates),version:VERSION})}
 const jobs={'/v1/lab/archive-batch':['archive',()=>collectArchiveBatch(env.DB)],'/v1/lab/history-priority-batch':['history',()=>scheduledCollection(env.DB)],'/v1/lab/learning-experiment-batch':['learning',()=>scheduledExperiment(env.DB)],'/v1/lab/result-priority-batch':['results',()=>scheduledRichResult(env.DB)],'/v1/lab/result-source-batch':['results',()=>discoverResultSource(env.DB)]};
 if(jobs[u.pathname]&&request.method==='POST'){const b=await request.json();if(b.confirm!==(u.pathname.includes('learning')?'BATCH':'COLLECT'))throw Error('確認指定が必要です。');const [job,work]=jobs[u.pathname];return json({...await runPipelineJob(env.DB,job,'manual',work),version:VERSION})}
 if(['/v1/lab/history-result-batch','/v1/lab/result-enrich'].includes(u.pathname)&&request.method==='POST'){const b=await request.json();if(!['COLLECT','INGEST'].includes(b.confirm))throw Error('確認指定が必要です。');return json({...await runPipelineJob(env.DB,'results','manual',()=>collectRichResult(env.DB,b)),version:VERSION})}
 if(u.pathname==='/v1/lab/result-day-enrich'&&request.method==='POST'){const b=await request.json();if(b.confirm!=='INGEST')throw Error('confirm INGEST is required');const before=await richResultStatus(env.DB,b.date),r=before.details.find(x=>!x.richComplete),result=r?await runPipelineJob(env.DB,'results','manual',()=>collectRichResult(env.DB,{date:b.date,venue:r.venue,raceNo:r.race_no})):{ok:true,status:'complete',externalRequests:0};return json({ok:result.ok,date:b.date,processed:r?[result]:[],status:await richResultStatus(env.DB,b.date),version:VERSION})}
}catch(e){return json({ok:false,error:String(e.message||e),version:VERSION},400)}
const response=await app.fetch(request,env,ctx);let d;try{d=await response.clone().json()}catch{if(u.pathname==='/lab/result-collection')return new Response((await response.text()).replace('毎時45分','最大10分ごと').replace('毎時45分','最大10分ごと'),{status:response.status,headers:response.headers});return response}if(d&&typeof d==='object')d.version=VERSION;return json(d,response.status)},async scheduled(event,env,ctx){const jobs={'2,12,22,32,42,52 * * * *':['archive',()=>collectArchiveBatch(env.DB)],'5,15,25,35,45,55 * * * *':['history',()=>scheduledCollection(env.DB)],'0,10,20,30,40,50 * * * *':['learning',()=>scheduledExperiment(env.DB)],[RESULT_CRON]:['results',()=>scheduledRichResult(env.DB)]};if(jobs[event.cron]){const [job,work]=jobs[event.cron];ctx.waitUntil(runPipelineJob(env.DB,job,'scheduled',work,{scheduledTime:event.scheduledTime}).then(r=>console.log(job,r.status)).catch(e=>{console.error(job,String(e));throw e}));return}return app.scheduled(event,env,ctx)}};
