import app from './index-v3.8.7.js';
import {sha256,requireLockEvidence} from './card-evidence.js';
export const VERSION='3.8.8';
export const MARK_PHASES=['initial','post_draw','final'];
export const MARKS=['◎','○','▲','△','☆','注','消'];
const H={'content-type':'application/json; charset=UTF-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'};
const json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:H});
export const numericOrNull=v=>v===null||v===undefined||v===''?null:(Number.isFinite(Number(v))?Math.round(Number(v)*10)/10:null);
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'');
async function rows(db,q,a=[]){try{return((await db.prepare(q).bind(...a).all()).results||[])}catch{return[]}}
async function one(db,q,a=[]){try{return await db.prepare(q).bind(...a).first()}catch{return null}}
const stable=v=>JSON.stringify(sort(v));function sort(v){return Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v}

export function normalizeMarks(x={}){
 const phase=String(x.phase||'');if(!MARK_PHASES.includes(phase))throw new Error(`phase must be ${MARK_PHASES.join('/')}`);
 const track=x.track?String(x.track):null;if(phase==='final'&&!track)throw new Error('final phase requires explicit track');
 if(!Array.isArray(x.marks)||!x.marks.length||x.marks.length>18)throw new Error('marks must contain 1-18 entries');
 const seen=new Set(),marks=x.marks.map((m,i)=>{const horseNo=m.horseNo==null?null:Number(m.horseNo),horseName=m.horseName?String(m.horseName).trim():null,mark=String(m.mark||'');if(horseNo!==null&&(!Number.isInteger(horseNo)||horseNo<1||horseNo>18))throw new Error(`marks[${i}].horseNo invalid`);if(!horseNo&&!horseName)throw new Error(`marks[${i}] needs horseNo or horseName`);if(!MARKS.includes(mark))throw new Error(`marks[${i}].mark invalid`);const k=horseNo?`n:${horseNo}`:`h:${horseName}`;if(seen.has(k))throw new Error('duplicate marked runner');seen.add(k);return{horseNo,horseName,mark,note:m.note?String(m.note).slice(0,500):null,ordinal:i+1}});
 return{phase,track,marks,warnings:['◎','○'].filter(s=>marks.filter(x=>x.mark===s).length>1).map(s=>`multiple-${s}-marks`)};
}
export function markAlignment(mark,rank){
 const r=Number(rank);if(!Number.isInteger(r)||r<1)return{level:'unscored',reviewPriority:'medium',reason:'LABO rank unavailable'};
 if(mark==='◎')return r<=3?{level:'aligned',reviewPriority:'low',reason:'◎ inside LABO top 3'}:r<=6?{level:'watch',reviewPriority:'high',reason:'◎ outside LABO top 3'}:{level:'conflict',reviewPriority:'critical',reason:'◎ is LABO rank 7+'};
 if(mark==='○')return r<=4?{level:'aligned',reviewPriority:'low',reason:'○ inside LABO top 4'}:r<=7?{level:'watch',reviewPriority:'medium',reason:'○ outside LABO top 4'}:{level:'conflict',reviewPriority:'high',reason:'○ is LABO rank 8+'};
 if(mark==='消')return r<=4?{level:'conflict',reviewPriority:'critical',reason:'消 conflicts with LABO top 4'}:r<=7?{level:'watch',reviewPriority:'high',reason:'消 removes LABO top 7'}:{level:'aligned',reviewPriority:'low',reason:'消 outside LABO top 7'};
 return r<=8?{level:'aligned',reviewPriority:'low',reason:`${mark} inside LABO top 8`}:{level:'watch',reviewPriority:'medium',reason:`${mark} outside LABO top 8`};
}
async function ensure(db){
 await db.prepare(`CREATE TABLE IF NOT EXISTS lab_user_mark_revisions(revision_id TEXT PRIMARY KEY,race_key TEXT NOT NULL,phase TEXT NOT NULL,revision_no INTEGER NOT NULL,track_condition TEXT,identity_basis TEXT NOT NULL,mark_payload_sha256 TEXT NOT NULL,audit_sha256 TEXT NOT NULL,audit_json TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(race_key,phase,revision_no))`).run();
 await db.prepare(`CREATE TABLE IF NOT EXISTS lab_user_mark_entries(revision_id TEXT NOT NULL,race_key TEXT NOT NULL,phase TEXT NOT NULL,horse_no INTEGER,horse_name TEXT NOT NULL,mark TEXT NOT NULL,note TEXT,ordinal INTEGER NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(revision_id,horse_name))`).run();
 await db.prepare('CREATE INDEX IF NOT EXISTS idx_user_mark_rev ON lab_user_mark_revisions(race_key,phase,revision_no DESC)').run();
}
async function resolve(db,t){return one(db,'SELECT race_key,race_date,venue,race_no,race_name,runner_count FROM jra_races WHERE race_date=? AND venue=? AND race_no=?',[t.date,t.venue,t.raceNo])}
async function target(db,t){return one(db,'SELECT race_key,race_date,venue,race_no,race_name FROM lab_precard_targets WHERE race_date=? AND venue=? AND race_no=?',[t.date,t.venue,t.raceNo])}
async function history(db,date,names){const clean=[...new Set(names.filter(Boolean))];if(!clean.length)return new Map();const q=clean.map(()=>'?').join(',');return new Map((await rows(db,`SELECT horse_name,COUNT(race_date) n FROM jra_past_performances WHERE race_date<? AND horse_name IN (${q}) GROUP BY horse_name`,[date,...clean])).map(x=>[x.horse_name,Number(x.n||0)]))}

export async function auditUserMarks(db,t,input){
 const n=normalizeMarks(input),race=await resolve(db,t);
 if(!race){
  if(n.phase!=='initial')throw new Error('post_draw/final marks require official numbered card');const pre=await target(db,t);if(!pre)throw new Error('race not found');
  const c=await rows(db,'SELECT horse_name,sex,age,trainer,stable,sire,dam,damsire,focus_text,source_sha256 FROM lab_precard_runner_context WHERE race_key=? AND active_in_latest=1',[pre.race_key]);if(!c.length)throw new Error('pre-card runner context is not published/stored yet');const by=new Map(c.map(x=>[x.horse_name,x])),hs=await history(db,pre.race_date,n.marks.map(x=>x.horseName));
  const marked=n.marks.map(m=>{if(m.horseNo!==null)throw new Error('horse numbers cannot be used before official card');const p=by.get(m.horseName);if(!p)throw new Error(`marked horse not in pre-card context: ${m.horseName}`);const h=hs.get(m.horseName)||0,w=[];if(h<2)w.push(h===0?'zero-pre-race-history':'one-pre-race-history');return{horseNo:null,horseName:m.horseName,mark:m.mark,note:m.note,laboRank:null,laboScore:null,alignment:markAlignment(m.mark,null),profile:{sex:p.sex,age:p.age,trainer:p.trainer,stable:p.stable,pedigree:{sire:p.sire,dam:p.dam,damsire:p.damsire},jraFocusText:p.focus_text},evidence:{historyRows:h,sourceSha256:p.source_sha256},warnings:w}});
  return{ok:true,version:VERSION,stage:'user-mark-db-crosscheck',race:{raceKey:pre.race_key,date:pre.race_date,venue:pre.venue,raceNo:Number(pre.race_no),raceName:pre.race_name},phase:n.phase,identityBasis:'precard-non-authoritative',inputWarnings:n.warnings,scoreMutation:false,audit:{mode:'precard-context-only',decisionReady:false,marked,summary:{unscored:marked.length},unmarkedTopCandidates:[],trackBias:null,guardrails:{userMarksNeverMutateModelScore:true,officialNumberedCardStillRequired:true,horseNumbersNeverInferred:true}}};
 }
 const off=await rows(db,'SELECT horse_no,frame_no,horse_name,sex,age,assigned_weight,jockey,trainer FROM jra_runners WHERE race_key=? ORDER BY horse_no',[race.race_key]);if(!off.length||off.length!==Number(race.runner_count))throw new Error('official numbered card is incomplete');
 const evidence=await requireLockEvidence(db,race,off);
 const bn=new Map(off.map(x=>[Number(x.horse_no),x])),bname=new Map(off.map(x=>[x.horse_name,x));
 const marked=n.marks.map(m=>{const a=m.horseNo?bn.get(m.horseNo):null,b=m.horseName?bname.get(m.horseName):null,h=a||b;if(!h)throw new Error('marked runner not found on official card');if(a&&b&&Number(a.horse_no)!==Number(b.horse_no))throw new Error('horseNo/horseName mismatch');return{...m,horseNo:Number(h.horse_no),horseName:h.horse_name,meta:h}});
 let track=n.track;if(!track)track=(await one(db,"SELECT track_condition FROM lab_integrated_snapshots WHERE race_key=? AND model_version='2.3.0' ORDER BY generated_at DESC LIMIT 1",[race.race_key]))?.track_condition||null;
 const integ=track?await rows(db,"SELECT * FROM lab_integrated_snapshots WHERE race_key=? AND model_version='2.3.0' AND track_condition=? ORDER BY prefinal_points DESC,horse_no",[race.race_key,track]):[],base=track?await rows(db,"SELECT horse_no,model_coverage_pct,confidence_pct,generated_at FROM lab_prediction_snapshots WHERE race_key=? AND model_version='1.5.0' AND track_condition=?",[race.race_key,track]):[],pace=await rows(db,"SELECT horse_no,style_label,pace_bias,lane_bias,bias_confidence,raw_fit_score,pace_style_fit_score,evidence_confidence,generated_at FROM lab_pace_style_snapshots WHERE race_key=? AND model_version='1.8.0'",[race.race_key]),cond=await rows(db,"SELECT horse_no,evidence_confidence,signals_available,generated_at FROM lab_condition_prep_snapshots WHERE race_key=? AND model_version='2.3.0'",[race.race_key]),bias=await one(db,"SELECT * FROM lab_track_bias_snapshots WHERE race_key=? AND model_version='1.7.0' ORDER BY generated_at DESC LIMIT 1",[race.race_key]),pre=await rows(db,'SELECT horse_name,stable,sire,dam,damsire,focus_text,source_sha256 FROM lab_precard_runner_context WHERE race_key=? AND active_in_latest=1',[race.race_key]),hs=await history(db,race.race_date,marked.map(x=>x.horseName));
 const im=new Map(integ.map((x,i)=>[Number(x.horse_no),{x,rank:i+1}])),bm=new Map(base.map(x=>[Number(x.horse_no),x])),pm=new Map(pace.map(x=>[Number(x.horse_no),x])),cm=new Map(cond.map(x=>[Number(x.horse_no),x])),pr=new Map(pre.map(x=>[x.horse_name,x]));
 const audited=marked.map(m=>{const z=im.get(m.horseNo),i=z?.x||{},b=bm.get(m.horseNo)||{},p=pm.get(m.horseNo)||{},c=cm.get(m.horseNo)||{},q=pr.get(m.horseName)||{},h=hs.get(m.horseName)||0,w=[];if(h<2)w.push(h===0?'zero-pre-race-history':'one-pre-race-history');if(b.confidence_pct!=null&&Number(b.confidence_pct)<60)w.push('low-base-confidence');if(!z)w.push('integrated-model-snapshot-missing');return{horseNo:m.horseNo,horseName:m.horseName,mark:m.mark,note:m.note,laboRank:z?.rank||null,laboScore:numericOrNull(i.prefinal_points),alignment:markAlignment(m.mark,z?.rank),profile:{frameNo:m.meta.frame_no,jockey:m.meta.jockey,trainer:m.meta.trainer,assignedWeight:m.meta.assigned_weight,sex:m.meta.sex,age:m.meta.age,stable:q.stable||null,pedigree:q.sire?{sire:q.sire,dam:q.dam,damsire:q.damsire}:null,jraFocusText:q.focus_text||null},components:{basic:numericOrNull(i.basic_score),recent:numericOrNull(i.recent_score),paceStyle:numericOrNull(i.pace_style_score),courseDistance:numericOrNull(i.course_distance_score),ground:numericOrNull(i.ground_score),condition:numericOrNull(i.condition_prep_score)},evidence:{historyRows:h,modelCoveragePct:numericOrNull(b.model_coverage_pct),baseConfidencePct:numericOrNull(b.confidence_pct),style:p.style_label||null,paceBias:p.pace_bias||null,laneBias:p.lane_bias||null,biasConfidence:p.bias_confidence||null,paceFit:numericOrNull(p.pace_style_fit_score),paceEvidenceConfidence:p.evidence_confidence||null,conditionEvidenceConfidence:c.evidence_confidence||null,conditionSignals:c.signals_available??null},warnings:w}});
 const set=new Set(marked.map(x=>x.horseNo)),unmarked=integ.slice(0,8).map((x,i)=>({x,rank:i+1})).filter(z=>!set.has(Number(z.x.horse_no))).slice(0,3).map(z=>({laboRank:z.rank,horseNo:Number(z.x.horse_no),horseName:z.x.horse_name,laboScore:numericOrNull(z.x.prefinal_points)}));
 const modelCoveragePct=race.runner_count?Math.round(integ.length/race.runner_count*1000)/10:0,decisionReady=modelCoveragePct===100&&Boolean(track);
 return{ok:true,version:VERSION,stage:'user-mark-db-crosscheck',race:{raceKey:race.race_key,date:race.race_date,venue:race.venue,raceNo:Number(race.race_no),raceName:race.race_name,runnerCount:Number(race.runner_count)},phase:n.phase,identityBasis:'official-numbered-card-evidence-verified',inputWarnings:n.warnings,scoreMutation:false,audit:{mode:'official-card-model-crosscheck',decisionReady,trackAssumption:track,trackBasis:n.track?'user-explicit':'latest-integrated-snapshot',modelCoveragePct,officialCardEvidence:{sourceSha256:evidence.source_sha256,runnerSha256:evidence.runner_sha256,declaredCount:evidence.declared_count,countBasis:evidence.count_basis,cardFetchedAt:evidence.card_fetched_at,verifiedAt:evidence.verified_at},dataFreshness:{integratedGeneratedAt:integ[0]?.generated_at||null,baseGeneratedAt:base[0]?.generated_at||null,paceGeneratedAt:pace[0]?.generated_at||null,conditionGeneratedAt:cond[0]?.generated_at||null,trackBiasGeneratedAt:bias?.generated_at||null},trackBias:bias?{paceBias:bias.pace_bias,laneBias:bias.lane_bias,confidence:bias.confidence,analyzedRaces:bias.analyzed_races,top3CornerSamples:bias.top3_corner_samples}:null,marked:audited,unmarkedTopCandidates:unmarked,highReviewCount:audited.filter(x=>['high','critical'].includes(x.alignment.reviewPriority)).length,summary:{aligned:audited.filter(x=>x.alignment.level==='aligned').length,watch:audited.filter(x=>x.alignment.level==='watch').length,conflict:audited.filter(x=>x.alignment.level==='conflict').length,unscored:audited.filter(x=>x.alignment.level==='unscored').length},guardrails:{userMarksNeverMutateModelScore:true,userMarksNeverChangeLABORank:true,auditReadsStoredModelEvidenceOnly:true,officialCardFingerprintRequired:true}}};
}
async function save(db,t,x){await ensure(db);const a=await auditUserMarks(db,t,x),cur=await one(db,'SELECT COALESCE(MAX(revision_no),0) n FROM lab_user_mark_revisions WHERE race_key=? AND phase=?',[a.race.raceKey,a.phase]),rev=Number(cur?.n||0)+1,id=`${a.race.raceKey}|${a.phase}|${rev}`,stamp=new Date().toISOString(),marks=a.audit.marked.map((m,i)=>({horseNo:m.horseNo,horseName:m.horseName,mark:m.mark,note:m.note,ordinal:i+1})),actualTrack=a.audit.trackAssumption||x.track||null,payloadSha=await sha256(stable({raceKey:a.race.raceKey,phase:a.phase,track:actualTrack,marks})),auditJson=stable(a),auditSha=await sha256(auditJson),st=[db.prepare('INSERT INTO lab_user_mark_revisions(revision_id,race_key,phase,revision_no,track_condition,identity_basis,mark_payload_sha256,audit_sha256,audit_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,a.race.raceKey,a.phase,rev,actualTrack,a.identityBasis,payloadSha,auditSha,auditJson,stamp),...marks.map(m=>db.prepare('INSERT INTO lab_user_mark_entries(revision_id,race_key,phase,horse_no,horse_name,mark,note,ordinal,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,a.race.raceKey,a.phase,m.horseNo,m.horseName,m.mark,m.note,m.ordinal,stamp))];if(db.batch)await db.batch(st);else for(const q of st)await q.run();return{...a,stage:'user-mark-saved-and-crosschecked',revisionNo:rev,revisionId:id,markPayloadSha256:payloadSha,auditSha256:auditSha,storageAtomic:Boolean(db.batch)}}
async function latest(db,t,phase){await ensure(db);const race=await resolve(db,t)||await target(db,t);if(!race)return{ok:false,version:VERSION,error:'race not found'};const ps=phase?[phase]:MARK_PHASES,out=[];for(const p of ps){if(!MARK_PHASES.includes(p))throw new Error('invalid phase');const v=await one(db,'SELECT * FROM lab_user_mark_revisions WHERE race_key=? AND phase=? ORDER BY revision_no DESC LIMIT 1',[race.race_key,p]);if(!v)continue;const e=await rows(db,'SELECT horse_no,horse_name,mark,note,ordinal FROM lab_user_mark_entries WHERE revision_id=? ORDER BY ordinal',[v.revision_id]);let a=null;try{a=JSON.parse(v.audit_json)}catch{}out.push({phase:p,revisionNo:Number(v.revision_no),revisionId:v.revision_id,trackCondition:v.track_condition,identityBasis:v.identity_basis,entries:e,audit:a})}return{ok:true,version:VERSION,stage:'user-mark-history',raceKey:race.race_key,latest:out,scoreMutation:false}}
function tgt(v){const date=String(v.date||''),venue=String(v.venue||''),raceNo=Number(v.raceNo??v.race_no);if(!validDate(date)||!venue||!Number.isInteger(raceNo)||raceNo<1||raceNo>12)throw new Error('date, venue, raceNo=1-12 required');return{date,venue,raceNo}}
async function body(req){if(Number(req.headers.get('content-length')||0)>65536)throw new Error('body too large');try{return await req.json()}catch{throw new Error('valid JSON required')}}
function auth(req,env){if(!env.USER_MARK_WRITE_TOKEN)throw Object.assign(new Error('user-mark writes disabled until USER_MARK_WRITE_TOKEN configured'),{status:503});const got=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(got!==env.USER_MARK_WRITE_TOKEN)throw Object.assign(new Error('unauthorized user-mark write'),{status:401})}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(u.pathname==='/')return json({ok:true,service:'keiba-lab-api',version:VERSION,phase:'human marks x verified LABO DB evidence'});if(u.pathname==='/v1/lab/deploy-check')return json({ok:true,version:VERSION,build:'user-mark-official-evidence-hardening',now:new Date().toISOString()});if(u.pathname==='/v1/lab/user-mark-capabilities')return json({ok:true,version:VERSION,phases:MARK_PHASES,marks:MARKS,writeProtection:'Bearer secret + confirm=SAVE',writeReady:Boolean(env.USER_MARK_WRITE_TOKEN),principles:{humanMarksAreIndependentInput:true,scoreMutation:false,officialCardRequiredForPostDrawAndFinal:true,officialCardEvidenceRequired:true,initialCanUseIsolatedPrecardNames:true,horseNumbersNeverInferredBeforeOfficialCard:true,auditSnapshotPersistedWithRevision:true,nullEvidenceNeverPresentedAsZero:true}});if(!env.DB)return json({ok:false,version:VERSION,error:'D1 DB missing'},500);try{if(u.pathname==='/v1/lab/user-mark-audit'&&req.method==='POST'){const b=await body(req);return json(await auditUserMarks(env.DB,tgt(b),b))}if(u.pathname==='/v1/lab/user-marks'&&req.method==='POST'){auth(req,env);const b=await body(req);if(b.confirm!=='SAVE')return json({ok:false,version:VERSION,error:'confirm=SAVE required'},400);return json(await save(env.DB,tgt(b),b))}if(u.pathname==='/v1/lab/user-marks'&&req.method==='GET')return json(await latest(env.DB,tgt({date:u.searchParams.get('date'),venue:u.searchParams.get('venue'),raceNo:u.searchParams.get('race_no')}),u.searchParams.get('phase')));return app.fetch(req,env,ctx)}catch(e){return json({ok:false,version:VERSION,error:String(e.message||e),scoreMutation:false},Number(e.status)||(/official|pre-card|race not found|Prospective LOCK/.test(String(e))?409:400))}},async scheduled(e,env,ctx){return app.scheduled(e,env,ctx)}};
