import app from './index-v3.12.0.js';import {deriveRaceReadiness} from './readiness-v3.13.0.js';
export const VERSION='3.13.0';const H={'content-type':'application/json; charset=UTF-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'};const json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:H});const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'');
async function one(db,q,a=[]){try{return await db.prepare(q).bind(...a).first()}catch{return null}}
async function sub(app,request,env,ctx,path){const u=new URL(request.url);u.pathname=path;const r=await app.fetch(new Request(u.href,{method:'GET'}),env,ctx);try{return await r.json()}catch{return null}}
async function readiness(request,env,ctx,u){const date=u.searchParams.get('date'),venue=u.searchParams.get('venue'),raceNo=Number(u.searchParams.get('race_no')||u.searchParams.get('raceNo'));if(!validDate(date)||!venue||!Number.isInteger(raceNo)||raceNo<1||raceNo>12)return{status:400,data:{ok:false,error:'date, venue, race_no=1-12 required'}};
 const race=await one(env.DB,'SELECT race_key,race_date,venue,race_no,race_name,runner_count FROM jra_races WHERE race_date=? AND venue=? AND race_no=?',[date,venue,raceNo]);if(!race)return{status:404,data:{ok:false,error:'race not found'}};
 const stored=await one(env.DB,'SELECT COUNT(*) n FROM jra_runners WHERE race_key=?',[race.race_key]);const marks=await one(env.DB,'SELECT COUNT(*) n,MAX(revision_no) latest FROM lab_user_mark_revisions WHERE race_key=?',[race.race_key]);const results=await one(env.DB,'SELECT COUNT(DISTINCT horse_no) n FROM lab_race_outcomes WHERE race_key=?',[race.race_key]);
 const pred=await sub(app,request,env,ctx,'/v1/lab/labo-prediction');const dl=await sub(app,request,env,ctx,'/v1/lab/decision-lab');const state=deriveRaceReadiness({declared:Number(race.runner_count||0),stored:Number(stored?.n||0),prediction:pred?.prediction?.available===true,userRevision:Number(marks?.n||0)>0,decisionLab:dl?.decisionLab?.available===true,resultRows:Number(results?.n||0)});
 return{status:200,data:{ok:true,version:VERSION,race:{raceKey:race.race_key,date:race.race_date,venue:race.venue,raceNo:Number(race.race_no),raceName:race.race_name,runnerCount:Number(race.runner_count||0)},storage:{storedRunnerRows:Number(stored?.n||0),resultRows:Number(results?.n||0)},prediction:{available:pred?.prediction?.available===true,locked:pred?.prediction?.locked===true,hashVerified:pred?.prediction?.hashVerified===true,sealedAt:pred?.prediction?.sealedAt||null},userMark:{available:Number(marks?.n||0)>0,latestRevision:marks?.latest==null?null:Number(marks.latest)},decisionLab:{available:dl?.decisionLab?.available===true,counterevidence:Number(dl?.decisionLab?.counterevidence?.length||0),missedHorses:Number(dl?.decisionLab?.missedHorses?.length||0)},readiness:state}}}
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(u.pathname==='/')return json({ok:true,service:'keiba-lab-api',version:VERSION,phase:'end-to-end race readiness'});if(u.pathname==='/v1/lab/deploy-check')return json({ok:true,version:VERSION,build:'race-readiness-pipeline',now:new Date().toISOString()});if(!env.DB)return json({ok:false,version:VERSION,error:'D1 DB missing'},500);try{if(u.pathname==='/v1/lab/race-readiness'&&request.method==='GET'){const r=await readiness(request,env,ctx,u);return json({...r.data,version:VERSION},r.status)}const r=await app.fetch(request,env,ctx);let d;try{d=await r.clone().json()}catch{return r}if(d&&typeof d==='object')d.version=VERSION;return json(d,r.status)}catch(e){return json({ok:false,version:VERSION,error:String(e?.message||e)},500)}},async scheduled(event,env,ctx){return app.scheduled(event,env,ctx)}};
