function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=UTF-8","access-control-allow-origin":"*","access-control-allow-methods":"GET, POST, OPTIONS","access-control-allow-headers":"Content-Type"}})}
function tokyoDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
async function fetchHtml(url){const r=await fetch(url,{headers:{"user-agent":"keiba-lab/0.9.0 (+official JRA racecard parser)",accept:"text/html,*/*;q=0.8"},redirect:"follow"});const b=await r.arrayBuffer();let body;try{body=new TextDecoder("shift_jis").decode(b)}catch{body=new TextDecoder("utf-8").decode(b)}return{ok:r.ok,status:r.status,url:r.url,contentType:r.headers.get("content-type"),bytes:b.byteLength,body}}
function text(s){return String(s||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/\s+/g," ").trim()}
function extractLinks(html,base){const out=[],seen=new Set(),re=/href\s*=\s*["']([^"'#]+)["']/gi;let m;while((m=re.exec(html))){try{const u=new URL(m[1].replace(/&amp;/g,"&"),base).href;if(!u.startsWith("https://www.jra.go.jp/")||seen.has(u))continue;seen.add(u);out.push(u)}catch{}}return out}
const BAD=new Set(["ニュース","企業情報","社会貢献活動","レース情報","新規会員登録","ホーム","競馬メニュー","レース成績データ","重賞レース一覧","スマートフォン","サイトマップ","リンク","ご利用に際して","ウェブアクセシビリティについて","成績データ"]);
function cleanName(s){return text(s).replace(/^\d+\s*/,"").trim()}
function plausibleHorseName(n){return n.length>=2&&n.length<=18&&/^[ァ-ヶー・ヴヷヸヹヺ]+$/.test(n)&&!BAD.has(n)}
function cellBlocks(row){return [...row.matchAll(/<(?:td|th)\b[^>]*>([\s\S]*?)<\/(?:td|th)>/gi)].map(m=>({html:m[1],text:text(m[1])}))}
function firstAnchorTexts(html){return [...html.matchAll(/<a\b[^>]*>([\s\S]*?)<\/a>/gi)].map(m=>cleanName(m[1])).filter(Boolean)}
function extractOfficialRunners(html){const runners=[],seen=new Set();for(const m of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const row=m[1],rt=text(row);if(!/父：/.test(rt)||!/母：/.test(rt))continue;const sexAge=rt.match(/(牡|牝|せん)\s*([2-9])/);if(!sexAge)continue;const cells=cellBlocks(row);if(cells.length<3)continue;let horseCell=null,profileCell=null;for(const c of cells){if(!horseCell&&/父：/.test(c.text)&&/母：/.test(c.text))horseCell=c;if(!profileCell&&/(牡|牝|せん)\s*[2-9]/.test(c.text)&&/(4[89]|5[0-9]|6[0-2])(?:\.\d)?\s*(?:kg|キロ)/i.test(c.text))profileCell=c}if(!horseCell||!profileCell)continue;const horseAnchors=firstAnchorTexts(horseCell.html);const name=horseAnchors.find(plausibleHorseName)||null;if(!name||seen.has(name))continue;const jockeyAnchors=firstAnchorTexts(profileCell.html).filter(x=>x!==name&&!plausibleHorseName(x));const allAnchors=firstAnchorTexts(row);let trainer=null;for(const a of horseAnchors){if(a!==name&&/[一-龠々]/.test(a)){trainer=a;break}}const jockey=jockeyAnchors[0]||allAnchors.find(a=>a!==name&&a!==trainer&&/[一-龠々]/.test(a)&&a.length<=12)||null;const numberCells=cells.map(c=>c.text).filter(v=>/^(?:[1-9]|1[0-8])$/.test(v)).map(Number);const horseNo=numberCells.length?numberCells[numberCells.length-1]:null;const frameNo=numberCells.length>1?numberCells[0]:null;const ptxt=profileCell.text;const saIndex=ptxt.search(/(牡|牝|せん)\s*[2-9]/);const weightPart=saIndex>=0?ptxt.slice(saIndex,saIndex+80):ptxt;const wm=weightPart.match(/(4[89]|5[0-9]|6[0-2])(?:\.([05]))?\s*(?:kg|キロ)/i);const assignedWeight=wm?Number(wm[1]+(wm[2]?"."+wm[2]:"")):null;runners.push({frameNo,horseNo,name,sex:sexAge[1],age:Number(sexAge[2]),assignedWeight,jockey,trainer,rowText:rt.slice(0,260)});seen.add(name)}return runners}
function parseOfficialRacecard(page){const t=text(page.body);const title=text(page.body.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]);const venue=(t.match(/(札幌|函館|福島|新潟|東京|中山|中京|京都|阪神|小倉)/)||[])[1]||null;const raceNo=Number((t.match(/(?:^|\s)(1[0-2]|[1-9])レース(?:\s|$)/)||[])[1]||0)||null;const surface=(t.match(/コース：[^。]{0,80}(芝|ダート|障害)/)||[])[1]||null;const distance=Number((t.match(/コース：[^0-9]{0,30}([123][0-9]{3})メートル/)||[])[1]||0)||null;let raceName=null;for(const h of page.body.matchAll(/<h[12][^>]*>([\s\S]*?)<\/h[12]>/gi)){const x=text(h[1]);if(x&&x!=="出馬表"&&!/関連メニュー|検索/.test(x)&&x.length<=40){raceName=x.replace(/^第\d+回/,m=>m);if(/毎日王冠|京都大賞典|ステークス|賞|未勝利|新馬|クラス|オープン/.test(x))break}}const runners=extractOfficialRunners(page.body);return{sourceUrl:page.url,title,raceName,venue,raceNo,surface,distance,runnerCount:runners.length,runners}}
function officialSeeds(date){if(date==="2026-10-04")return[
 {label:"東京11R 毎日王冠",url:"https://www.jra.go.jp/JRADB/accessD.html?CNAME=pw01dde0105202604021120261004%2FC5"},
 {label:"京都11R 京都大賞典",url:"https://www.jra.go.jp/JRADB/accessD.html?CNAME=pw01dde0108202604021120261004%2FA3"}
];return[]}
async function officialProbe(){const date=tokyoDate(),seeds=officialSeeds(date);if(!seeds.length)return{ok:false,stage:"official-racecard",version:"0.9.0",date,error:"No official seed configured for this date"};const races=[],sameDayLinks=new Set();for(const seed of seeds){try{const p=await fetchHtml(seed.url);if(!p.ok){races.push({label:seed.label,sourceUrl:seed.url,error:`HTTP ${p.status}`});continue}for(const u of extractLinks(p.body,p.url)){if(u.includes("/JRADB/accessD.html")&&u.includes(date.replaceAll("-","")))sameDayLinks.add(u)}races.push({label:seed.label,...parseOfficialRacecard(p)})}catch(e){races.push({label:seed.label,sourceUrl:seed.url,error:String(e)})}}const totalRunners=races.reduce((n,r)=>n+(r.runnerCount||0),0);return{ok:races.some(r=>r.runnerCount>0),stage:"official-runner-parse",version:"0.9.0",date,seedCount:seeds.length,discoveredSameDayRacecardLinks:sameDayLinks.size,totalRunners,races,next:"If runner lists are clean, generalize same-day racecard crawl and persist verified rows to D1"}}
async function inspectSchema(db){const tr=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%' ORDER BY name").all(),tables=[];for(const row of tr.results||[]){const n=String(row.name);if(!/^[A-Za-z0-9_]+$/.test(n))continue;tables.push({name:n,columns:(await db.prepare(`PRAGMA table_info(${n})`).all()).results||[]})}return tables}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:{"access-control-allow-origin":"*"}});const u=new URL(request.url);try{if(u.pathname==="/")return json({ok:true,service:"keiba-lab-api",version:"0.9.0",phase:"official JRA racecard parser",missing:env.DB?[]:["D1 binding: DB"]});if(!env.DB)return json({ok:false,error:"D1 binding DB is not configured"},500);if(u.pathname==="/health"||u.pathname==="/api/health"){const r=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all();return json({ok:true,database:"connected",tables:r.results})}if(u.pathname==="/v1/schema"){const tables=await inspectSchema(env.DB);return json({ok:true,database:"connected",tableCount:tables.length,tables})}if(u.pathname==="/v1/jra/test"){const seeds=officialSeeds(tokyoDate());if(!seeds.length)return json({ok:false,error:"No seed for today"},404);const r=await fetchHtml(seeds[0].url);return json({source:"JRA JRADB",ok:r.ok,status:r.status,bytes:r.bytes,url:r.url},r.ok?200:502)}if(u.pathname==="/v1/jra/ingest"||u.pathname==="/v1/jra/discover")return json(await officialProbe());if(u.pathname==="/v1/meetings/today"){const date=tokyoDate(),r=await env.DB.prepare("SELECT venue, race_date, COUNT(*) AS race_count FROM races WHERE race_date=? GROUP BY venue,race_date ORDER BY venue").bind(date).all();return json({ok:true,date,meetings:r.results})}if(u.pathname==="/api/races"){const r=await env.DB.prepare("SELECT * FROM races ORDER BY race_date DESC,venue,race_no LIMIT 100").all();return json({ok:true,count:r.results.length,data:r.results})}if(u.pathname==="/api/predictions"){const r=await env.DB.prepare("SELECT * FROM predictions ORDER BY id DESC LIMIT 100").all();return json({ok:true,count:r.results.length,data:r.results})}if(u.pathname==="/api/validations"){const r=await env.DB.prepare("SELECT * FROM validations ORDER BY id DESC LIMIT 100").all();return json({ok:true,count:r.results.length,data:r.results})}return json({ok:false,error:"Not Found"},404)}catch(e){return json({ok:false,error:String(e),stack:e?.stack||null},500)}},async scheduled(event,env,ctx){ctx.waitUntil(officialProbe().then(r=>console.log("JRA official ingestion probe",JSON.stringify({ok:r.ok,stage:r.stage,totalRunners:r.totalRunners,links:r.discoveredSameDayRacecardLinks}))).catch(e=>console.error("JRA ingestion failed",String(e))))}};