import {comparisonPage as previousPage} from './mark-comparison-page-v3.41.0.js';
import {EXPECTED_SOURCES} from './expected-runner-preview-v3.30.0.js';
export function comparisonPage(source=EXPECTED_SOURCES[0]){
 let page=previousPage(source);
 const target=JSON.stringify({date:source.date,venue:source.venue,raceNo:source.raceNo,snapshotId:source.snapshotId,names:source.names,reviewMeta:source.reviewMeta||{official:false,frameVerified:false,roster:[]}}).replace(/</g,'\\u003c');
 page=page.replace(/(<script type="application\/json" id="comparisonTarget">)[\s\S]*?(<\/script>)/,(_,a,b)=>a+target+b);
 page=page.replace('<section id="allRunnerTable"></section>','<section class="card" aria-labelledby="reviewHeading"><h2 id="reviewHeading">見直しの記録と変化</h2><p class="meta">初期印→枠順後→当日の見直しを、このブラウザで記録できます。正式な印保存・事前LOCKとは別です。</p><div class="review-controls"><label>記録の段階<select id="reviewPhase" aria-label="記録の段階"><option value="initial">初期印</option><option value="post_draw">枠順後の見直し</option><option value="race_day">当日の見直し</option></select></label><button type="button" id="recordComparison" disabled>今の比較を記録</button></div><p id="recordStatus" role="status"></p><p id="reviewCount" class="meta"></p><label>比較する記録<select id="reviewBaseline" aria-label="比較する記録"><option value="">記録を選んで比較</option></select></label><div id="reviewDelta"></div><p class="meta">枠順後は全馬の枠番を照合した正式出馬表、当日は開催日の正式出馬表が必要です。見直し記録は予測精度の検証には使いません。</p></section><section id="allRunnerTable"></section>');
 page=page.replace('</style>','.review-controls{display:flex;gap:12px;align-items:end;flex-wrap:wrap}.review-controls label{flex:1}#reviewPhase,#reviewBaseline{display:block;width:100%;margin:6px 0 12px}#recordComparison{margin-bottom:12px}#recordStatus{color:var(--accent)}.frame-badge{display:inline-block;border:1px solid #8793a0;border-radius:4px;font-size:12px;padding:2px 5px;color:#111}.frame-1{background:#fff}.frame-2{background:#111;color:#fff}.frame-3{background:#c92b34;color:#fff}.frame-4{background:#1b5ebd;color:#fff}.frame-5{background:#efcc21}.frame-6{background:#248754;color:#fff}.frame-7{background:#ec9430}.frame-8{background:#e888b4}#reviewDelta table{min-width:900px} </style>');
 return page;
}
