const clean=v=>String(v??'').replace(/\r/g,'').trim();const val=(c,...keys)=>{for(const k of keys)if(c?.[k]!=null&&Number.isFinite(Number(c[k])))return Number(c[k]);return null};const fmt=v=>v==null?'—':`${v>0?'+':''}${Math.round(v*100)/100}`;const stage=(r,id)=>Boolean((r?.stages||[]).find(x=>x.id===id)?.ready);
export function composeFullPredictionNote({race={},prediction={},decisionLab={},readiness={}}={}){
 const title=`${race.date||''} ${race.venue||''}${race.raceNo||''}R ${race.raceName||''}`.trim(),top=prediction.top5||[],why=decisionLab.why||[],marks=why.filter(x=>x.userMark);const lines=[`🏇 ${title}`,'','【出走前ステータス】',`公式出馬表：${readiness.cardComplete?'✓ 保存・監査済み':'○ 確認待ち'}`,`LABO予想：${prediction.available?'🔒 発走前LOCK済み':'○ LOCK前'}`,`想定馬場：${clean(prediction.trackCondition||'未設定')}`,`哲平印：${stage(readiness,'user-mark')?'✓ 保存済み':'○ 未入力'}`,`DB再精査：${decisionLab.available?'✓ 完了':'○ 待機'}`,'','【KEIBA LABO 印】'];
 if(top.length)for(const x of top)lines.push(`${x.mark||''} ${x.horseNo||''} ${clean(x.horseName)}${x.score==null?'':`　LABO ${x.score}pt`}`);else lines.push('事前LOCK後に表示します。');
 lines.push('','【馬場・展開・位置取りチェック】');if(top.length){for(const x of top){const c=x.components||{};lines.push(`・${x.mark||''}${clean(x.horseName)}：馬場 ${fmt(val(c,'track','ground','heavy'))} / 展開 ${fmt(val(c,'pace','paceStyle'))} / 位置 ${fmt(val(c,'position'))} / 距離 ${fmt(val(c,'distance','courseDistance'))} / コース ${fmt(val(c,'course','courseDistance'))} / 追切 ${fmt(val(c,'workout','condition'))}`)}}else lines.push('LOCKデータ待ち');
 lines.push('','【哲平印 × LABO再精査】');if(marks.length)for(const x of marks)lines.push(`${x.userMark} ${x.horseNo} ${clean(x.horseName)}　LABO ${x.laboRank??'—'}位${x.laboScore==null?'':` / ${x.laboScore}pt`}`);else lines.push('哲平印はまだ保存されていません。');
 const ce=decisionLab.counterevidence||[],miss=decisionLab.missedHorses||[];lines.push('','【反証】');if(ce.length)for(const x of ce)lines.push(`⚠️ ${x.userMark||''} ${clean(x.horseName)}：${(x.reasons||[]).join(' / ')||'再確認'}`);else lines.push('現時点で強い反証なし。');lines.push('','【見逃し候補】');if(miss.length)for(const x of miss)lines.push(`👀 ${x.horseNo} ${clean(x.horseName)}　LABO ${x.laboRank}位`);else lines.push('現時点でLABO上位のUSER無印なし。');
 lines.push('','【買い目設計】');const main=marks.find(x=>x.userMark==='◎'),opp=marks.find(x=>x.userMark==='○'),others=marks.filter(x=>['▲','△','☆','注'].includes(x.userMark));if(main&&opp){const hs=others.map(x=>`${x.horseNo}${clean(x.horseName)}`).join('・')||'相手未設定';lines.push(`勝負軸：◎ ${main.horseNo}${clean(main.horseName)}`,`相手軸：○ ${opp.horseNo}${clean(opp.horseName)}`,`相手候補：${hs}`,'三連単フォーメーション／保険マルチ／三連複は、オッズと予算確認後に最終確定。');}else lines.push('◎○確定後に買い目候補を組み立てます。');lines.push('資金配分：未確定（購入前に予算・点数・オッズを確認）','','※発走前に保存されたデータだけで作成。結果から事前印・LABO順位・スコアを書き換えません。','※欠けている評価項目は「—」のまま表示し、0点として扱いません。');return lines.join('\n').replace(/\n{3,}/g,'\n\n').trim();
}
