export function pipelineHeartbeat(run,now){if(!run)return 'not-observed';const age=now-Number(run.started_at);if(age>30*60000)return 'overdue';if(run.status==='running')return age>5*60000?'completion-unconfirmed':'running';return 'observed';}
export async function runPipelineJob(db,job,trigger,work,{scheduledTime=Date.now(),now=Date.now,runId=null}={}){
 await db.prepare('CREATE TABLE IF NOT EXISTS lab_bounded_pipeline_runs(run_id TEXT PRIMARY KEY,job TEXT NOT NULL,trigger_kind TEXT NOT NULL,started_at INTEGER NOT NULL,finished_at INTEGER,status TEXT NOT NULL,result_json TEXT,error TEXT)').run();
 await db.prepare('CREATE INDEX IF NOT EXISTS lab_pipeline_job_started ON lab_bounded_pipeline_runs(job,trigger_kind,started_at)').run();
 const id=runId||(trigger==='scheduled'?job+':'+scheduledTime:'manual:'+crypto.randomUUID()),stamp=now();const insert=await db.prepare("INSERT OR IGNORE INTO lab_bounded_pipeline_runs(run_id,job,trigger_kind,started_at,status) VALUES(?,?,?,?,'running')").bind(id,job,trigger,stamp).run();if(Number(insert.meta?.changes)!==1)return{ok:true,status:'already-recorded',externalRequests:0};
 try{const result=await work();await db.prepare('UPDATE lab_bounded_pipeline_runs SET finished_at=?,status=?,result_json=? WHERE run_id=?').bind(now(),result.status||(result.ok===false?'failed':'complete'),JSON.stringify(result),id).run();return result}catch(e){await db.prepare("UPDATE lab_bounded_pipeline_runs SET finished_at=?,status='failed',error=? WHERE run_id=?").bind(now(),String(e.message||e).slice(0,4000),id).run();throw e}
}
export async function pipelineStatus(db,now=Date.now()){
 let rows;try{rows=(await db.prepare('SELECT p.* FROM lab_bounded_pipeline_runs p WHERE p.run_id=(SELECT q.run_id FROM lab_bounded_pipeline_runs q WHERE q.job=p.job AND q.trigger_kind=p.trigger_kind ORDER BY q.started_at DESC,q.run_id DESC LIMIT 1) ORDER BY p.job,p.trigger_kind').all()).results||[]}catch(e){if(!/no such table/.test(String(e)))throw e;rows=[]}
 return{checkedAt:new Date(now).toISOString(),jobs:['archive','history','results','learning'].map(job=>{const scheduled=rows.find(x=>x.job===job&&x.trigger_kind==='scheduled'),manual=rows.find(x=>x.job===job&&x.trigger_kind==='manual');const present=r=>r?{startedAt:new Date(r.started_at).toISOString(),finishedAt:r.finished_at?new Date(r.finished_at).toISOString():null,status:r.status,error:r.error||(r.result_json?JSON.parse(r.result_json).error:null),result:r.result_json?JSON.parse(r.result_json):null}:null;return{job,heartbeat:pipelineHeartbeat(scheduled,now),scheduled:present(scheduled),manual:present(manual)}}),manualRunsProveCron:false}
}
