import {experimentStatus,EXPERIMENT} from './learning-experiment-v3.40.0.js';
import {pipelineStatus} from './pipeline-runs-v3.40.0.js';
import {archiveStatus} from './archive-collection-v3.39.0.js';
import {pickSourceJob} from './source-coordinator-v3.40.0.js';
import {jstDay} from './history-collection-v3.37.0.js';
async function optionalRows(db,sql,args=[]){try{return{available:true,rows:(await db.prepare(sql).bind(...args).all()).results||[]};}catch(e){if(!/no such table/i.test(String(e)))throw e;return{available:false,rows:[]};}}
export function classifyMissingHistory(receipt){
 if(!receipt)return{state:'not-checked',label:'プロフィール未確認'};
 if(receipt.status==='failed')return{state:'retry',label:'取得・照合を保留。再確認待ち'};
 if(receipt.status==='checked'&&Number(receipt.rows_found)===0)return{state:'checked-empty',label:'プロフィール確認済み。対象日前の履歴を取得できず'};
 if(['checked','stored-enough'].includes(receipt.status))return{state:'stored',label:'履歴取得済み。学習条件の照合待ち'};
 return{state:'unknown',label:'収集記録の状態を確認中'};
}
export async function workProgress(db,now=Date.now()){
 const pipeline=await pipelineStatus(db,now),experiment=await experimentStatus(db),archive=await archiveStatus(db),nextSourceJob=await pickSourceJob(db),today=jstDay(now);
 let historyQueue=await optionalRows(db,"SELECT t.*,l.status learning_status FROM lab_history_collection_targets t LEFT JOIN lab_learning_collection_receipts l ON l.race_key=t.race_key AND l.experiment_id=? WHERE t.status='pending' OR (t.date>=? AND COALESCE(t.last_run_at,0)<?) ORDER BY CASE WHEN t.date>=? THEN 0 WHEN l.status='awaiting-prior-history' THEN 1 ELSE 2 END,CASE WHEN l.status='awaiting-prior-history' THEN json_array_length(l.missing_history_json) ELSE 999 END,COALESCE(t.last_run_at,0),t.date,t.race_no DESC LIMIT 1",[EXPERIMENT.id,today,now-86400000,today]);
 if(!historyQueue.available)historyQueue=await optionalRows(db,"SELECT * FROM lab_history_collection_targets WHERE status='pending' OR (date>=? AND COALESCE(last_run_at,0)<?) ORDER BY CASE WHEN date>=? THEN 0 ELSE 1 END,COALESCE(last_run_at,0),date,race_no DESC LIMIT 1",[today,now-86400000,today]);
 const waiting=experiment.collection?.waiting||[],keys=waiting.map(x=>x.raceKey);let receipts={available:true,rows:[]};
 if(keys.length)receipts=await optionalRows(db,'SELECT race_key,horse_name,status,rows_found,checked_at FROM lab_history_collection_receipts WHERE race_key IN ('+keys.map(()=>'?').join(',')+') LIMIT 216',keys);
 const resultCoverage=await optionalRows(db,"SELECT race_date,COUNT(*) races,SUM(CASE WHEN runner_count>0 AND detail_rows=runner_count AND detail_distinct=runner_count THEN 1 ELSE 0 END) complete_results,SUM(last3f_missing) last3f_missing,SUM(corners_missing) corners_missing FROM (SELECT r.race_date,r.race_key,r.runner_count,COUNT(d.horse_no) detail_rows,COUNT(DISTINCT d.horse_no) detail_distinct,SUM(CASE WHEN d.finish_position IS NOT NULL AND (d.last3f IS NULL OR d.last3f<=0) THEN 1 ELSE 0 END) last3f_missing,SUM(CASE WHEN d.finish_position IS NOT NULL AND (d.corner_positions IS NULL OR d.corner_positions='') THEN 1 ELSE 0 END) corners_missing FROM jra_races r LEFT JOIN lab_race_result_details d ON d.race_key=r.race_key WHERE r.race_date IN (SELECT DISTINCT race_date FROM jra_races ORDER BY race_date DESC LIMIT 10) GROUP BY r.race_key) GROUP BY race_date ORDER BY race_date DESC");
 return{ok:true,checkedAt:new Date(now).toISOString(),pipeline,nextSourceJob,historyQueue:{available:historyQueue.available,candidate:historyQueue.rows[0]||null,meaning:'保存済みキューの次候補。実行時の取得制限・更新により変わります。'},archive,results:resultCoverage,learning:{initialized:experiment.initialized,training:experiment.trainingReadiness||null,minimumRaces:EXPERIMENT.minimumTrainingRaces,minimumDays:EXPERIMENT.minimumTrainingDays,candidateCreated:Boolean(experiment.candidate),validation:experiment.validation||null,minimumValidationRaces:EXPERIMENT.minimumValidationRaces,minimumValidationDays:EXPERIMENT.minimumValidationDays,validationFrom:EXPERIMENT.validationFrom,waiting:waiting.map(w=>({...w,horses:(w.missingHistoryHorses||[]).map(horseName=>{const receipt=receipts.rows.find(r=>r.race_key===w.raceKey&&r.horse_name===horseName);return{horseName,...(receipts.available?classifyMissingHistory(receipt):{state:'unknown',label:'プロフィール収集記録は未確認'}),rowsFound:receipt?Number(receipt.rows_found):null,lastCheckedAt:receipt?.checked_at?new Date(receipt.checked_at).toISOString():null};})}))},guardrails:{readOnly:true,externalRequests:0,missingHistoryNotEquivalentToUnraced:true,automaticPromotion:false,accuracyImprovementValidated:false},remainingImplementation:{frameScoreCorrection:'未実装・検証待ち',automaticMemoTraining:'未実装',crossBrowserMemoSync:'未実装（現在はブラウザ内保存）'}};
}
